instruction update for java devs
Umuzi-org/ACN-syllabus pull request #1015
Opened 2023-05-19 09:41 UTC by Sbonelo01

## Description:
Some java developers only submit the function in an attempt to follow the instructions. This PR tries to address that.

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-05-22 10:28 UTC, sheenarbw requested changes
It's a good try, but not specific enough.

2023-05-22 10:28 UTC, sheenarbw commented on content/projects/katas/level-1/_index.md
> +- Even though the instructions will specifically ask for a function, please don't submit only the function/method. Make sure that there is a wrapping public class in your code.
Please add examples. 

The learners will either put everything in the same class or spread all the functions out across multiple files.  The learners will end up guessing.  It's important to be very very explicit about what is required here. 

Please reach out to @ruddy-m  to ask her if you aren't sure how the code should be structured.

2023-05-23 09:19 UTC, Sbonelo01 commented
@ruddy-m , please review when you can

2023-06-01 09:52 UTC, sheenarbw requested changes
Some strange text formatting, otherwise it's fine

2023-06-01 09:52 UTC, sheenarbw commented on content/projects/katas/level-1/_index.md
> +- Even though the instructions will specifically ask for a function, please don't submit only the function/method. Make sure that there is a wrapping public class for your function/method.
Why does this need a bullet point?

2023-06-09 07:48 UTC, ruddy-m commented on content/projects/katas/level-1/_index.md
> +- **For those using Javascript:** Make sure they export their functions correctly. Otherwise, the marking bot won't be able to access their functions.
this should also be JavaScript

2023-06-09 07:48 UTC, ruddy-m approved these changes

2023-06-13 07:11 UTC, sheenarbw approved these changes

2023-06-13 07:12 UTC, merged