remove react lavour on react specilisation - tilde mockups
Umuzi-org/ACN-syllabus pull request #1018
Opened 2023-05-30 03:40 UTC by ry-oc

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-06-13 08:11 UTC, sheenarbw requested changes
But now it is not accurate. They are meant to do it in react

2023-06-13 08:11 UTC, sheenarbw commented on content/syllabuses/react-specialisation.md
> -- {{< contentlink path="projects/tilde-mockups" flavour="javascript,react" >}}
But they are meant to do it in react.

2023-07-28 10:11 UTC, TheMaja approved these changes

2023-07-28 10:15 UTC, TheMaja commented on content/syllabuses/react-specialisation.md
> +- {{< contentlink path="projects/tilde-mockups" flavour="react,javascript" >}}
It should be just 'React' since React itself is built with JavaScript. No need to mention both 'React' and 'JavaScript' separately.

2023-07-28 10:16 UTC, TheMaja commented on content/syllabuses/react-specialisation.md
> +- {{< contentlink path="projects/recipe-search/part-2" flavour="react,javascript" >}}
It should be just 'React' since React itself is built with JavaScript. No need to mention both 'React' and 'JavaScript' separately.

2023-07-28 10:17 UTC, TheMaja requested changes
apologize for the earlier approval.
- It should be just 'React' since React itself is built with JavaScript. No need to mention both 'React' and 'JavaScript' separately.

2023-08-01 12:21 UTC, sheenarbw approved these changes

2023-08-01 12:21 UTC, sheenarbw commented on content/syllabuses/react-specialisation.md
> +- {{< contentlink path="projects/recipe-search/part-2" flavour="react,javascript" >}}
You can use React and Typescript together. You have experienced this yourself @TheMaja .

2023-08-01 12:22 UTC, merged