Update _index.md
Umuzi-org/ACN-syllabus pull request #1064
Opened 2023-06-29 17:18 UTC by Faancy

Related issues: [please specify]

## Description: A picture and a security picture

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-06-30 02:36 UTC, sheenarbw requested changes
This one looks a bit rushed. Please always take a minute to check that you would approve the PR

2023-06-30 02:36 UTC, sheenarbw commented on content/tech-big-picture/security-best-practices-for-you/_index.md
> +![best security practices](security.png)
where is security.png? I'm not seeing it in the repo so this picture will be broken. Did you forget to add it to your PR?

2023-06-30 02:36 UTC, sheenarbw commented on content/tech-big-picture/security-best-practices-for-you/_index.md
> +- 9how to protect your privacy from hackers, spies, and the government)[https://www.zdnet.com/article/online-security-101-how-to-protect-your-privacy-from-hackers-spies-and-the-government/]
Typo here. `9how `should be `(how`

2023-06-30 08:04 UTC, Faancy commented on content/tech-big-picture/security-best-practices-for-you/_index.md
> +![best security practices](security.png)
I just added it to the branch.

2023-07-04 08:56 UTC, sheenarbw approved these changes

2023-07-04 08:56 UTC, merged