removed module 10 solo learn python deprecated
Umuzi-org/ACN-syllabus pull request #1098
Opened 2023-08-03 08:43 UTC by Lisa1400

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-08-08 11:00 UTC, Ngoakor12 requested changes
I can't spot any major issues, just one thing...

- Should the new python solo learn stuff not be plugged into the active syllabuses?

2023-08-17 10:18 UTC, Ngoakor12 approved these changes

2023-08-22 03:56 UTC, ry-oc reviewed
Good work :) 1 question, are there any points where we confirm that they have completed a course? 

Maybe we should add 2 profile check cards?

2023-08-22 03:56 UTC, ry-oc commented on content/topics/solo-learn/python/intro-to-python/1-getting-started-with-python/index.md
> +
Maybe add instructions for the reviewer?

2023-08-22 03:56 UTC, ry-oc commented on content/topics/solo-learn/python/intro-to-python/2-going-deeper-with-python/index.md
> +  - topics/solo-learn/python/intro-to-python/1-getting-started-with-python
Change this to a soft pre-req or they wont be able to start this until we move the pre-req to complete

2023-08-22 03:56 UTC, ry-oc commented on content/topics/solo-learn/python/python-intermediate/1-collection-types/index.md
> +We just need to make sure everyone is keeping up 💚
needs instructions for reviewer

2023-08-22 03:56 UTC, ry-oc commented on content/topics/solo-learn/python/python-intermediate/2-functional-programming/index.md
> +  - topics/solo-learn/python/python-intermediate/1-collection-types
change to soft pre-req

2023-08-23 06:50 UTC, Lisa1400 commented
@ry-oc I didn't change the hard pre-reqs to soft pre-reqs because the hard pre-req links are topics and not projects.

2023-08-23 07:48 UTC, Ngoakor12 requested changes
I think we can be a little bit more specific regarding the instructions for reviewers depending on the profile check card, E.g:
- `Make sure they've submitted a link to their sololearn profile(not just any link)`

For the profile checks cards at the start of courses(first module in intro course, same with first module in intermediate course), include something like:
-` Make sure the course is in the "Courses Progress" section on the sololern profile`

For the end of course profile check cards, include something like:
- `Make sure the course is in the "Certificates" section on the sololern profile`

Otherwise the linter is passing and previous changes seem to have been addressed/explained

2023-08-23 09:19 UTC, Ngoakor12 approved these changes

2023-08-25 03:31 UTC, ry-oc requested changes
Looks like you forgot to add the profile check to the syllabuses?

2023-08-29 12:49 UTC, ry-oc commented on content/syllabuses/bootcamp-data-sci-boot-quick-wins.md
> +- {{< contentlink path="topics/solo-learn/python/intro-to-python/1-getting-started-with-python" >}}
@Lisa1400 I don't see the project on any of the syllabuses

2023-09-01 07:55 UTC, Ngoakor12 reviewed
Project checks added to syllabuses :heavy_check_mark: 

Can you also merge develop into this branch to avoid previous linter errors please.

2023-09-04 06:42 UTC, Lisa1400 commented
@Ngoakor12 I merged develop into my branch. But when I typed `git status` it showed "nothing to commit, working tree clean".

2023-09-04 07:06 UTC, Ngoakor12 commented
> @Ngoakor12 I merged develop into my branch. But when I typed `git status` it showed "nothing to commit, working tree clean".

Try this:

- checkout to `develop` first: `git checkout develop`
- pull main changes locally: `git pull`
- go back to your branch: `git checkout <your-branch>`
- merge develop: `get merge develop`
- push the merged changes: `git push`

2023-09-05 11:14 UTC, Ngoakor12 approved these changes

2023-09-06 04:59 UTC, ry-oc approved these changes

2023-09-18 14:45 UTC, sheenarbw approved these changes

2023-09-18 14:45 UTC, merged