Assertive prog for data sci
Umuzi-org/ACN-syllabus pull request #1100
Opened 2023-08-04 13:08 UTC by Samantha-Hampton

Related issues: [please specify]

## Description:

Added assertive programming project for pandas into data sci syllabus 

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes. ** I'm having issues probably getting the server to run for the develop branch
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-08-08 12:40 UTC, Lisa1400 approved these changes
I ran linter on my side. Everything looks good to me!

2023-08-14 07:03 UTC, sheenarbw requested changes
It looks a bit repetitive.

Is it in fact a prerequisite? If yes then use prerequisites. 
If the ordering is more like a recommendation then it's better to put it in the syllabus index pages.

I don't see the benefit of doing both. Maybe I'm missing something? 

We also need to figure out how to get the site working on your computer. You might just be running the wrong version of Hugo.  Can you please check if the issue exists on the live site? If it does then please make a Task so that it can be fixed.

2023-08-14 09:33 UTC, Samantha-Hampton commented
> It looks a bit repetitive.
> 
> Is it in fact a prerequisite? If yes then use prerequisites. If the ordering is more like a recommendation then it's better to put it in the syllabus index pages.
> 
> I don't see the benefit of doing both. Maybe I'm missing something?
> 
> We also need to figure out how to get the site working on your computer. You might just be running the wrong version of Hugo. Can you please check if the issue exists on the live site? If it does then please make a Task so that it can be fixed.

Have removed from syllabus index, I do want them do to if before stats thinking and after data wrangling so that should now be all good.

My issue of content links going nowhere doesn't seem to be happening on the live site.
But I have downloaded the latest Hugo and followed the latest ACN-syllabus repo readme for Mac setup. I'm not sure if there is anyone else running a Mac to check with, but perhaps it is in fact a Mac problem - who is best placed to assist me with troubleshooting?

2023-08-21 06:36 UTC, sheenarbw approved these changes

2023-08-21 06:36 UTC, merged