showing learners how to use an HTML validator
Umuzi-org/ACN-syllabus pull request #1108
Opened 2023-08-25 05:30 UTC by Sbonelo01

Related issues: https://www.notion.so/your-first-html-page-Show-learners-how-to-validate-their-html-with-an-online-validator-2db8f11cacc0485e9441fa7db0f37bda?pvs=4

## Description: I changed the formatter to use because the HTML validator from W3C even shows warnings and some useful info.

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2023-08-25 10:35 UTC, Ngoakor12 requested changes
Nice work on the video...

- I think the information hierarchy can be improved
```
// current
...
1. Create a new HTML file called `index.html`
2. Let's make some content
...

// suggestion
...
1. Create a new HTML file called `index.html`
2. Let's add some content
3. Clean and validate the code
...
```

2023-08-25 10:35 UTC, Ngoakor12 commented on content/zmc-challenges/first-website/your-first-html-page/_index.md
>  ### 2.1 Add a `<head>` element
This heading should be a level 4 since it falls under `2. Let's make some content `

2023-08-25 10:35 UTC, Ngoakor12 commented on content/zmc-challenges/first-website/your-first-html-page/_index.md
> +- Make use of an online HTML validator to check your own work. Here is a validator: https://validator.w3.org/ and [here[(https://www.youtube.com/watch?v=XXecps3jEVw) is a video to show you how to mak
The video link is not linked correctly:
![image](https://github.com/Umuzi-org/ACN-syllabus/assets/54069197/a9481b70-74cc-4ea3-b92e-0f121443d492)

2023-08-31 07:12 UTC, Ngoakor12 reviewed
headings still not flowing right, please double check

2023-08-31 07:24 UTC, Ngoakor12 commented on content/zmc-challenges/first-website/your-first-html-page/_index.md
> +- Make use of an online HTML validator to check your own work. Here is a validator: https://validator.w3.org/ and [here](https://www.youtube.com/watch?v=XXecps3jEVw) is a video showing you how to use
One small issue I just noticed, can you please make the first link is also markdown for consistency

2023-08-31 07:34 UTC, Ngoakor12 approved these changes

2023-09-19 11:14 UTC, sheenarbw approved these changes

2023-09-19 11:14 UTC, merged