added curly brackets to match the intructions
Umuzi-org/ACN-syllabus pull request #1115
Opened 2023-08-31 10:30 UTC by FaithMo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)
The change is in line 113, the rest of the file is auto formatted.

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2023-08-31 10:59 UTC, Ngoakor12 requested changes
- The way the function is being called is technically not correct...
- There's also a closely related ticket [here](https://www.notion.so/Consume-github-API-add-language-specific-examples-ea4acba515d2456f8a89a11c52b97af8?pvs=4) so maybe add calls for the other languages too?
- I think [the Person project instructions with example calls](http://syllabus.africacode.net/projects/oop/person/#:~:text=Example%20usage%3A,SSD%20hard%20drives.) are a good reference

2023-09-05 06:59 UTC, FaithMo commented
> * The way the function is being called is technically not correct...
> * There's also a closely related ticket [here](https://www.notion.so/Consume-github-API-add-language-specific-examples-ea4acba515d2456f8a89a11c52b97af8?pvs=4) so maybe add calls for the other languages too?
> * I think [the Person project instructions with example calls](http://syllabus.africacode.net/projects/oop/person/#:~:text=Example%20usage%3A,SSD%20hard%20drives.) are a good reference

Ohhh of course, destructuring :) I'm dumb lol

Let me have a look at that ticket and discern what to do

2023-09-12 08:46 UTC, Ngoakor12 requested changes

2023-09-12 08:46 UTC, Ngoakor12 commented on content/projects/github-api-consume/part1/_index.md
> +})
python example should not have curly braces

2023-09-12 08:46 UTC, Ngoakor12 commented on content/projects/github-api-consume/part1/_index.md
> +)
this is a function call so you need to pass in actual values here... E.g:
```java
getPullRequests("Umuzi-org",....)
```

2023-11-09 12:00 UTC, TheMaja approved these changes

2023-11-13 06:19 UTC, sheenarbw approved these changes

2023-11-13 06:19 UTC, merged