added instructions for testing react projects
Umuzi-org/ACN-syllabus pull request #1118
Opened 2023-09-04 15:59 UTC by TheMaja

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-09-05 12:54 UTC, Ngoakor12 reviewed
The are some more projects missing(E.g. Recipe projects? if they need to tested then mention it, if not then leave them). I also updated the ticket title to make more sense.

2023-09-07 11:19 UTC, Ngoakor12 requested changes
- The topic you are linking to is using enzyme only. If we want the learners to choose, then it might be worth also adding some resources for [react testing library](https://testing-library.com/docs/react-testing-library/intro/) which is recommended by the react authors as well

2023-09-07 11:19 UTC, Ngoakor12 commented on content/projects/recipe-search/part-2/_index.md
> +Please test your code, you will be expected to use a react testing library to test your components, here is the documentation {{< contentlink path="topics/web-frontend/react/unit-testing" >}}.
I think this can be added as part of the instructions... so maybe number 4

2023-09-07 11:19 UTC, Ngoakor12 commented on content/projects/recipe-search/part-1/_index.md
> +Please test your code, you will be expected to use a react testing library to test your components, here is the documentation {{< contentlink path="topics/web-frontend/react/unit-testing" >}}.
I think testing can be mentioned as butllet point 3 under the instructions heading

2023-09-08 04:59 UTC, Ngoakor12 requested changes
One last thing...

2023-09-08 04:59 UTC, Ngoakor12 commented on content/topics/web-frontend/react/unit-testing/_index.md
> +- https://www.youtube.com/watch?v=3e1GHCA3GP0
Please update the following links to markdown to make it more consistent with other links in the syllabus

2023-09-11 15:39 UTC, Ngoakor12 approved these changes

2023-09-15 05:57 UTC, sheenarbw approved these changes

2023-09-15 05:57 UTC, merged