updated function call instructions
Umuzi-org/ACN-syllabus pull request #1121
Opened 2023-09-07 11:40 UTC by TheMaja

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-09-08 05:08 UTC, Ngoakor12 requested changes
My understanding of the shopping cart issue is that we are using a different property name for the shopping baskets; `shoppingBaskets` on the automarker  and `allShoppingBaskets` on the instructions. So what ultimately needs to happen is that **we should choose one name for the shopping basket property** and make sure they match by either changing the instructions or automarker config.

Changin the ordering of what parameter comes first won't make a difference since we are using object destructuring instead of positional parameters. Here's [a resource](https://blog.bitsrc.io/javascript-why-named-arguments-are-better-than-positional-arguments-9b15ab3155ef)

2023-09-12 08:48 UTC, Ngoakor12 requested changes
Apologies I thought I had reviewed this one. I had added comments but didn't finalize the review

2023-09-12 08:48 UTC, Ngoakor12 commented on content/projects/understanding-loops/_index.md
> +function getCustomerBaskets({ shoppingBaskets, email }) {...}
please include the actual email address above here

2023-09-12 08:48 UTC, Ngoakor12 commented on content/projects/understanding-loops/_index.md
> +getCustomerBaskets({shoppingBaskets, email}) //DO THIS
same here

2023-09-15 05:45 UTC, Ngoakor12 requested changes

2023-09-15 05:45 UTC, Ngoakor12 commented on content/projects/understanding-loops/_index.md
> +function getCustomerBaskets({ shoppingBaskets, email }) {...}
missed this one

2023-09-15 06:43 UTC, Ngoakor12 approved these changes

2023-09-15 06:43 UTC, Ngoakor12 commented on content/projects/understanding-loops/_index.md
> +function getCustomerBaskets({ shoppingBaskets, email }) {...}
nevermind

2023-09-18 14:43 UTC, sheenarbw approved these changes

2023-09-18 14:43 UTC, merged