making questions clearer
Umuzi-org/ACN-syllabus pull request #1137
Opened 2023-09-19 13:56 UTC by Sbonelo01

Related issues: https://umuzi-projects.monday.com/boards/1254743632/pulses/1272950532

## Description:
When the markdown gets rendered, it looks clunky. This PR aims to fix that.

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2023-09-19 17:11 UTC, TheMaja commented on content/topics/test-driven-development-questions/_index.md
>  6. Take a look at the following code:
This can be rephrased into `Take a look at the following code snippets`

2023-09-19 17:13 UTC, TheMaja commented on content/topics/test-driven-development-questions/_index.md
> +expect(warningColour).not.toBe("blue)
include the closing `"blue"` to be in line with other languages.

2023-09-19 17:14 UTC, TheMaja requested changes
just a minor fix

2023-09-20 19:04 UTC, TheMaja approved these changes

2023-09-22 10:21 UTC, sheenarbw approved these changes

2023-09-22 10:21 UTC, merged