iOS mobile device content added
Umuzi-org/ACN-syllabus pull request #1150
Opened 2023-10-30 14:07 UTC by TheMaja

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-10-31 08:42 UTC, Sbonelo01 requested changes
Nicely done! Just something to note...

2023-10-31 08:42 UTC, Sbonelo01 commented on content/zmc-challenges/first-website/html-on-phone-or-computer/_index.md
> +- For an iOS device like an iPhone or iPad, you can use the [Koder](https://apps.apple.com/za/app/koder-code-editor/id1447489375) code editor. To learn how to use it, watch this [video](https://www.y
Our content strategy does allow us to make use of other resources as you have done here! Nice!

The problem is that there are a few bad practices in this video.

1. The file naming used here is not consistent with the ones we recommend that the students use.
2. The Syntax here is incorrect. The `head` tag is not closed properly.

Can you please try to look for another resource explaining Koder? If not, I will ask Sheena if this is sufficient

2023-11-02 08:05 UTC, Sbonelo01 approved these changes
`<html>` tag not closed properly still 😂, but this looks okay to me.

2023-11-06 08:45 UTC, sheenarbw approved these changes

2023-11-06 08:45 UTC, merged