iOS setup instructions for writing code on device
Umuzi-org/ACN-syllabus pull request #1159
Opened 2023-11-23 12:06 UTC by TheMaja

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-11-24 06:07 UTC, Ngoakor12 requested changes
1. Looking at the android setup, it looks like you are missing a few things:
- [x] code editor
- [ ] Topic: Python setup for IOS
- [ ] Topic: Javascript setup for IOS
- [ ] Topic: Java setup for IOS

Having at least one of those language setup shows that code will actually be successfully written with IOS. If not even one of the language setup can be done successfully then I don't know if it's worth saying we have an IOS setup at the moment.

2. Please also convert some of the links in this topic to use markdown

2023-11-28 08:56 UTC, Ngoakor12 requested changes
Nice! Almost there... 

Can we change iphone to "IOS" everywhere to inclusive of all devices that use IOS just like we have with Android. Make sure the change does not affect readability

2023-11-28 08:56 UTC, Ngoakor12 commented on content/environment-setup/git/_index.md
> +Start by installing Termux: [https://play.google.com/store/apps/details?id=com.termux&hl=en_ZA](https://play.google.com/store/apps/details?id=com.termux&hl=en_ZA)
Including the link in the square and round brackets defeats the whole purpose of markdown links and semantic html once everything is live. The text in the square brackets should be something descriptive that describes the link just like you did with the other links

2023-11-28 08:56 UTC, Ngoakor12 commented on content/environment-setup/git/_index.md
>  Note: Since November 2022, the Google Playstore has refused to accept updates from Termux, so downloading Termux from there won't work. You can download the latest version of Termux from [https://f-d
Same feedback regarding links here too

2023-11-29 05:02 UTC, Ngoakor12 requested changes
Almost there...

2023-11-29 05:02 UTC, Ngoakor12 commented on content/environment-setup/git/_index.md
you missed converting this link: https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ to be proper markdown

2023-11-29 15:35 UTC, Ngoakor12 approved these changes

2023-11-30 07:16 UTC, sheenarbw approved these changes

2023-11-30 07:16 UTC, sheenarbw commented on content/environment-setup/javascript-on-ios/_index.md
> +title: javaScript setup for iOS
javaScript should have a capital J

2023-11-30 07:17 UTC, merged