update java automarked projects for gradle init usage
Umuzi-org/ACN-syllabus pull request #1164
Opened 2023-12-11 10:46 UTC by Trevor27

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-12-13 14:45 UTC, kingraphaii requested changes

2023-12-13 14:45 UTC, kingraphaii commented on content/projects/oop/bank-accounts/part-2/_index.md
> +└── app
Should we not matc what we've put on other pages, like indicating the rest of the gradle config files and folders like we did here:

![image](https://github.com/Umuzi-org/ACN-syllabus/assets/57295227/bb37a5f0-a48c-40f4-8d3d-e1dc0239cf7c)

2024-01-09 10:16 UTC, Ngoakor12 requested changes
It looks like you forgot these project?
 - password checker
 - semitone
 - shopping cart

2024-01-09 10:16 UTC, Ngoakor12 requested changes
It looks like you forgot these project?
 - password checker
 - semitone
 - shopping cart calculations
 - consume github api

2024-01-09 11:24 UTC, Trevor27 commented
> It looks like you forgot these project?
> 
> * password checker
> * semitone
> * shopping cart calculations
> * consume github api

I have changed consume github api. Everything else has been updated already.

2024-01-10 09:44 UTC, Ngoakor12 commented
> > It looks like you forgot these project?
> > 
> > * password checker
> > * semitone
> > * shopping cart calculations
> > * consume github api
> 
> I have changed consume github api. Everything else has been updated already.

The directory structures have been updated, but some are missing explicit instructions to use gradle from the command line and a link to the gradle resources

2024-01-11 17:56 UTC, kingraphaii approved these changes

2024-01-12 09:02 UTC, sheenarbw requested changes
There seems to be some inconsistencies in the directory structures.

With some projects the structure is like this: EG: `app/src/main/java/string_calculator/StringCalculator.java`. So the project name is in there.

Other times it's like this:
`app/src/main/java/ShoppingCartCalculations.java`. In this case the project name is not in there.

That seems strange to me... is it different on purpose? What is the purpose?

2024-01-12 09:02 UTC, sheenarbw commented on content/projects/oop/animals/part1/_index.md
> +|       ├── main
Should this character be: └── instead of ├── ?  I think it would be good to be tidy.

This comes up in a few places, it should be very quick to clean up.

2024-01-12 09:02 UTC, sheenarbw commented on content/projects/understanding-loops/_index.md
> +
Are we sure this one is right? There is no project name?

2024-01-31 13:00 UTC, sheenarbw approved these changes

2024-01-31 13:01 UTC, merged