js usage examples
Umuzi-org/ACN-syllabus pull request #1166
Opened 2024-01-29 15:45 UTC by Ngoakor12

Related issues: [please specify]

## Description:

Adding language usage examples to help with the property naming and make sure learners name properties the way the automarker expects. Especially in javascript where using objects as restructured parameters is recommended

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-02-01 11:17 UTC, kingraphaii requested changes
Just needs a minor fix and fixing a merge conflict :)

2024-02-01 11:17 UTC, kingraphaii commented on content/projects/oop/bank-accounts/part-2/_index.md
> +The bank will need to keep track of which bank account is associated with with bank account number.
*with with :👀

2024-02-05 07:15 UTC, kingraphaii approved these changes

2024-02-05 10:08 UTC, sheenarbw approved these changes

2024-02-05 10:08 UTC, merged