DevOps Short Course Improvements
Umuzi-org/ACN-syllabus pull request #1201
Opened 2024-04-01 12:41 UTC by jonatasbaldin

## Description:
Improvements related to @sheenarbw's review from #1199.

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2024-04-02 14:35 UTC, sheenarbw requested changes

2024-04-02 14:35 UTC, sheenarbw commented on content/devops/foundational-short-course/8-devops-questions-2/_index.md
> +4. Can you list and describe the DevOps-type activities/tasks that you and your peers engage with?
Should this not be 1,2,3?

2024-04-02 16:42 UTC, jonatasbaldin commented on content/devops/foundational-short-course/8-devops-questions-2/_index.md
> +4. Can you list and describe the DevOps-type activities/tasks that you and your peers engage with?
Yep. Fixed.

2024-04-03 04:00 UTC, sheenarbw approved these changes

2024-04-03 04:00 UTC, merged