Quick Spelling and Font  fixes
Umuzi-org/ACN-syllabus pull request #1207
Opened 2024-04-25 14:25 UTC by CortanaV1

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-04-26 11:22 UTC, t-witchy approved these changes

2024-05-13 10:03 UTC, t-witchy commented on .vscode/settings.json
> +    "spellright.language": []
You must not commit anything in a .vscode folder.

2024-05-13 10:05 UTC, t-witchy approved these changes

2024-05-13 13:59 UTC, sheenarbw requested changes
This needs a bit of polish still.

2024-05-13 13:59 UTC, sheenarbw commented on content/topics/jasmine-unit-tests/_index.md
> +### Getting set up (Simple Method)
Sentence case is inconsistent

2024-05-13 13:59 UTC, sheenarbw commented on .vscode/settings.json
> +    "spellright.language": []
I agree. Please remove this from the PR

2024-05-13 13:59 UTC, sheenarbw commented on content/specific-skill-success-criteria/for-loops/_index.md
> +### JS and Java learners understand that they can count up and down.
This should not be at this heading level. You are nesting it inside the "Note on Submission format" section. Please revert this change.

2024-05-13 13:59 UTC, sheenarbw commented on content/specific-skill-success-criteria/for-loops/_index.md
> +### JS and Java learners understand that they can count up and down.
Headings work like this:
```
## section 1
### section 1.1
### section 1.2
## section 2
```
If you put a level 3 heading after a level 2 heading then it says something very specific about the information hierarchy.  It's not just about looks.

2024-05-13 13:59 UTC, sheenarbw commented on content/topics/jasmine-unit-tests/_index.md
> +### Getting set up (Complex Method)
It's not jsut complex, it's better. We never ask out learners to do things the complicated way just because it's complex.

We tell them that simple is better than complex.

Please choose different words here. 

Maybe beginner and advanced.

2024-05-14 08:08 UTC, CortanaV1 commented
Done

2024-05-17 05:24 UTC, sheenarbw requested changes
This still has heading hierarchy issues.

Play with google docs, look at how heading leavels effect how things appear in the document outline

2024-05-17 05:24 UTC, sheenarbw commented on content/specific-skill-success-criteria/for-loops/_index.md
> +### Python learners understand `range` and `in`.
Why is this heading nested under:  `## JS and Java learners understand that they can count up and down.` 
The hierarchy makes no sense.

These are distinct concepts

2024-05-17 05:24 UTC, sheenarbw commented on content/specific-skill-success-criteria/for-loops/_index.md
> +### Python learners understand `range` and `in`.
Either leave everything as heading level 2 or:

Make a new heading level 2 `## Concepts` and nest the different concepts under that.

Please try to put effort into understanding heading hierarchies.

It's like this:

```
## x
## y
### z
### a
```

This implies a tree structure:

```
x 

y
   z
   a
```

z and a are subheadings in the section titled y
z and a are inside y 

You are saying "All learners understand that the whole body of the loop executes on each iteration." is inside "JS and Java learners understand that they can count up and down" which is cleartly wrong. These things are siblings, not parent child.

Please don't submit this kind of thing again. If you are still unclear on heading hierarchies I'm sure Whitney will be able to explain them to you. Never guess when submitting work. I simply will not merge things that are so clearly incorrect.

2024-05-17 05:24 UTC, sheenarbw commented on content/specific-skill-success-criteria/for-loops/_index.md
> +### All learners should understand the basics of while loops.
In most files, headings dont end with a full stop. Here they do. Can it be made more consistent?

2024-06-18 09:05 UTC, sheenarbw requested changes

2024-06-18 09:05 UTC, sheenarbw commented on content/specific-skill-success-criteria/for-loops/_index.md
> +### All learners should be able to reason about nested for loops.
Heading hierarchies are still incorrect

2024-06-18 10:29 UTC, merged