SQL initial update
Umuzi-org/ACN-syllabus pull request #1210
Opened 2024-06-18 11:18 UTC by Trevor27

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2024-06-20 11:44 UTC, Sbonelo01 requested changes
Looks good to me, but

For many learners, SQL is relatively a new thing. Can you please point learners to a good SQL best practices resource.

Also, a resources about Docker and  docker-compose. Many learners configure docker-compose.yaml file to make use of the adminer image but still instruct learners to download and install Postgres on their local machines in the documentation. It seems they aren't sure about the relationship of these technologies

2024-06-29 04:21 UTC, Ngoakor12 requested changes
Mostly looks good to me

2024-06-29 04:21 UTC, Ngoakor12 commented on content/sql/shop-project/_index.md
> +  Ensure the documentation reflects this setup correctly, so reviewers do not need to install Postgres locally. Refer to the following resource for more information: [How to Set Up Postgres and Admin
This part seems is important and should probably be higher up in the content, maybe under the `Installation` information.

2024-06-29 04:26 UTC, Ngoakor12 commented on content/sql/shop-project/_index.md
> +  Ensure the documentation reflects this setup correctly, so reviewers do not need to install Postgres locally. Refer to the following resource for more information: [How to Set Up Postgres and Admin
We also have a resource for setting docker up that's in the prerequisites so maybe relink that too(http://localhost:1313/docker/intro-to-docker/)

2024-07-02 10:36 UTC, Ngoakor12 approved these changes

2024-07-03 07:06 UTC, sheenarbw approved these changes

2024-07-03 07:07 UTC, merged