Add so and ac to ncit
Umuzi-org/ACN-syllabus pull request #147
Opened 2021-03-24 08:56 UTC by ry-oc

Related issues: [please specify]

## Description:

Adding the specific outcomes (SO) and corresponding assessment criteria (AC) to the NCIT topics

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors - my linter broke but there were no errors when i checked previously
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

A couple of things to note:

1. Some topics are linked to 2 unit standards, in this case I added the SO and AC for both with the lower unit standard at the top, this matches the order the unitstandards are listed in.
2. The unit standard for : content/national-qualifications-framework/ncit/presenting-your-findings/_index.md is formatted differently from all the others and the assessment criteria are unclear see: https://allqs.saqa.org.za/showUnitStandard.php?id=13925
3. I added pages for the informal assessments `Technical Report`, `Presentation Slides`, and `Research Notes` Based on the SO and AC these are required, currently we let them base this off the work they do in their design thinking sprint but this does not really work for anyone outside of umuzi.
4. I added pages for the `Final recap` Summative assessments but there is no content associated with them as they are just some questions the cover past content.

Additional Referances: https://allqs.saqa.org.za/showQualification.php?id=48872

2021-03-24 10:42 UTC, sheenarbw requested changes
Please remove unnecessary flavour stuff. Other than that it looks ok.

2021-03-24 10:42 UTC, sheenarbw commented on content/national-qualifications-framework/ncit/agile-meetings/_index.md
> +flavours:
rahter dont add flavours unless the project actually has flavours.

Is this coded? Does the language matter? 
Does this have a prerequisite that is coded? 

If you add flavours here then flavours need to be specified elsewhere and it has a knock on efect. It's better to be accurate and specific. No spray and pray

2021-03-24 10:42 UTC, sheenarbw commented on content/national-qualifications-framework/ncit/agile-project-management/_index.md
> +- any_language
ditto

2021-03-31 03:58 UTC, ry-oc commented
Gonna create a new branch and open a new PR, it will be easier than resolving merge conflicts

2021-03-31 03:58 UTC, closed without merging