instructions for person 108
Umuzi-org/ACN-syllabus pull request #163
Opened 2021-05-06 19:22 UTC by kaleem99

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-05-11 04:43 UTC, ry-oc requested changes
Almost there, some changes but also, please complete the template provided when you open a PR:

Related issues: [please specify] - this def relates to a issue.

 I ran the linter and there were no errors - did you not manage to run the linter?

2021-05-11 04:43 UTC, ry-oc commented on content/projects/oop/person/_index.md
> +## Instructions for reviewer
General clean code should become a habit for both the recruits as well as all reviewers. This should not need to be mentioned in every project. Please remove the instructions relating to general clean code guidelines and only leave the project-specific instructions.

Also please move the review instructions to below the Acceptance criteria.

2021-05-13 09:37 UTC, ry-oc commented on content/projects/oop/person/_index.md
> +## Instructions for reviewer
@kaleem99 please double-check, it looks like general clean code guidelines are still being included in the project review instructions

2021-05-18 04:57 UTC, ry-oc requested changes

2021-05-18 04:57 UTC, ry-oc commented on content/projects/oop/person/_index.md
> +3. **Competent or not yet competent** - If all of the instructions above have not been bet then the recruit should get a ``NYC`` with the instructions that have not been followed in his feedback.
Point 3 seems to be a general point that applies to all projects? Please can you remove it.

2021-05-20 04:33 UTC, ry-oc approved these changes

2021-05-20 06:10 UTC, sheenarbw requested changes
Your capitalisation is a little strange. Treat headings like normal English, dont capitalise everything, capitalise the first word and proper nouns.

Eg:
**Multiple Interests, Commas and Spacing**
Should be: **Multiple interests, commas and spacing**

2021-05-25 07:32 UTC, sheenarbw requested changes

2021-05-25 07:32 UTC, sheenarbw commented on content/projects/oop/person/_index.md
> +2. **Single interest or no interests** - Check if the class can work with single interests, and the string output should be different from the multiple interest output instead of `my interests are` i
To know something means to have knowledge of that thing. 

I have no interests means I have 0 interests.  'No' and 'know' mean very very different things.

2021-05-26 05:00 UTC, ry-oc approved these changes

2021-05-26 06:11 UTC, sheenarbw approved these changes

2021-05-26 06:11 UTC, merged