Git basic exercises instructions for reviewer
Umuzi-org/ACN-syllabus pull request #165
Opened 2021-05-07 09:45 UTC by Lisa1400

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-05-07 09:46 UTC, Lisa1400 commented
![Screenshot from 2021-05-07 11-46-27](https://user-images.githubusercontent.com/47818456/117431777-e7a80400-af29-11eb-8681-d98cacfb9ffd.png)

2021-05-11 04:30 UTC, ry-oc reviewed
Left a couple of comments for you :)

2021-05-11 04:30 UTC, ry-oc commented on content/projects/git-exercises/_index.md
> +- The history branch should consist of 2 files: README.md and history.txt.
there is an instruction to merge `main` into `history` this comes just before they add the .gitignore, so the history branch should contain the same as the main branch except the gitifnore

2021-05-11 04:30 UTC, ry-oc commented on content/projects/git-exercises/_index.md
> +- Ensure that there are 3 branches: main, history, and milkshake-flavours
I would add here that they should look at the network diagram

2021-05-11 04:33 UTC, ry-oc commented
Please also complete the related issues section of the pr, you left it blank implying this PR is not related to any issues

2021-05-13 09:36 UTC, ry-oc requested changes

2021-05-13 09:36 UTC, ry-oc commented on content/projects/git-exercises/_index.md
>   2. `README.md` should have `booya` in it.
Sorry, one thing I missed, we need to check for merge conflicts on readme

2021-05-13 09:36 UTC, ry-oc commented on content/projects/git-exercises/_index.md
> +- Take a look a the network diagram or graph.
what do we look for on the network diagram?

2021-06-02 03:23 UTC, ry-oc requested changes
Sorry, more changes based on some feedback I received from Sheena on other PRs

2021-06-02 03:23 UTC, ry-oc commented on content/projects/git-exercises/_index.md
> +- The history branch should consist of 3 files: README.md, history.txt and milkshakes.md. Consider that main should be merged into history before the .gitignore file is created.
Lets see if we can cut this down a bit, you can remove the specifics about what should be in history and milkshakes

2021-06-02 03:23 UTC, ry-oc commented on content/projects/git-exercises/_index.md
> + 3. `history.txt` should have the latest 1000 lines of commands typed on the person's local machine.
this can be removed as well

2021-06-02 03:23 UTC, ry-oc commented on content/projects/git-exercises/_index.md
> + 4. `milkshakes.md` should have 3 milkshake flavours in it.
and this

2021-06-02 03:23 UTC, ry-oc commented on content/projects/git-exercises/_index.md
> +- Ensure that there are 3 branches: main, history, and milkshake-flavours
Add a line to about the network diagram, we generally check that the branches are present and have been merged to main. We also check that main has been merged back into history.

2021-06-07 05:08 UTC, ry-oc approved these changes

2021-06-07 07:19 UTC, sheenarbw requested changes
This seems a bit nitpicky. If people are learning git for the fist time then we dont want to foce the to restart the project or break their heads untangling the messes theyare enevetably going to make. We dont need perfection here, we need the students to demonstrate understanding.

What do we need the student to UNDERSTAND here? How can we tell if they understand?

2021-06-22 08:07 UTC, ry-oc requested changes

2021-06-22 08:07 UTC, ry-oc commented on content/projects/git-exercises/_index.md
> +- Ensure that a recruit actually had a merge conflict to resolve by using the command `git show`.
Is this last point necessary?

2021-06-22 08:07 UTC, ry-oc commented on content/projects/git-exercises/_index.md
> +- Ensure that there are no merge conflict. If this kind of text `<<<<<<< HEAD` or `=======` appears, it indicates that merge conflicts were not resolved.
Appears where?

2021-06-22 08:07 UTC, ry-oc commented on content/projects/git-exercises/_index.md
> +- Check if there are multiple commits.
Is this point necessary? Is it not common sense for there to be multiple commits?

2021-07-14 04:00 UTC, ry-oc approved these changes

2021-08-05 05:56 UTC, sheenarbw requested changes
Other code schools use this content so we need to make use of language that works for other people. 

Don't say recruit, rather say "learner"

2021-08-05 05:56 UTC, sheenarbw commented on content/projects/git-exercises/_index.md
> +- Check if the recruit understands how merging works, by ensuring that the main branch has files merged into it. You can also take a look at the network diagram to check for merging.
try not to use the word "recruit". Rather say "learner"

2021-08-17 11:50 UTC, ry-oc approved these changes

2021-09-08 14:22 UTC, sheenarbw approved these changes

2021-09-08 14:24 UTC, merged