intructions to reviewer - string-calculator
Umuzi-org/ACN-syllabus pull request #167
Opened 2021-05-11 07:16 UTC by Sbonelo01

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2021-05-13 08:11 UTC, ry-oc requested changes
Small change

2021-05-13 08:11 UTC, ry-oc commented on content/projects/tdd/string-calculator/_index.md
> +- Code should be clean, DRY and should follow the KISS(Keep It Simple, Stupid) principal - look out for these when reviewing. Also ensure that they have used a tool like Prettier or Black to format t
The review instructions should be project specific.

Clean code conventions should not be mentioned in the review instructions as this relates to every project.

2021-05-25 06:47 UTC, ry-oc requested changes
3 tiny things, please Dm me when changes are made.

2021-05-25 06:47 UTC, ry-oc commented on content/projects/tdd/string-calculator/_index.md
> +- Make sure that the output is as per project instructions. Proper error handling to be used. no `print`, `console.log`. an error is to be thrown when needed and a value returned when needed.
Remove this piece: `Make sure that the output is as per project instructions.` as I think that is a given for any project :)

2021-05-25 06:47 UTC, ry-oc commented on content/projects/tdd/string-calculator/_index.md
> +- Ensure that the add function takes in the correct data-type as argument - the datatype should be a string.
Could this sentence be simplified to something like: `Ensure that the add function takes a string as an argument.

2021-05-25 06:47 UTC, ry-oc commented on content/projects/tdd/string-calculator/_index.md
> +- Tests are nessesary for this project. Proper testing to be followed. If someone uses mocks and spies - that is incompetent.
this part can be removed as it is in the project instructions: `Tests are nessesary for this project. `

2021-05-26 03:47 UTC, ry-oc approved these changes

2021-05-26 05:01 UTC, ry-oc approved these changes

2021-05-26 06:14 UTC, sheenarbw requested changes
- There is to be only one function. The `add()` function.

I disagree.  Making one long ass function is often bad practice. 

The `add` function needs to work. But if the learner decides to let `add` rely on other functions then that's totally fine. Often breaking a big function down into multiple smaller functions adds clarity, reusability and testability to the code.

2021-06-07 07:23 UTC, sheenarbw approved these changes

2021-06-07 07:23 UTC, merged