added instructions for reviewers for level 1 coding challenges
Umuzi-org/ACN-syllabus pull request #172
Opened 2021-05-12 11:09 UTC by Lisa1400

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-05-13 11:32 UTC, ry-oc approved these changes

2021-05-18 05:38 UTC, ry-oc requested changes
Hey, so a bunch of stuff is being repeated here. If the instruction exists in the project instruction then we can rely on the reviewer to read the instructions before reviewing

2021-05-18 05:38 UTC, ry-oc commented on content/projects/katas/level-1/_index.md
> +## Instructions for Reviewers
This is a bit too hi-res and you are repeating many of the instructions that are listed above, lets get this cleaned up :)

2021-05-18 05:38 UTC, ry-oc commented on content/projects/katas/level-1/_index.md
> +- Ensure that the logical operators are correct.
196 & 197 are repeats of the instructions above

2021-05-18 05:38 UTC, ry-oc commented on content/projects/katas/level-1/_index.md
> +- The number that you input should output that amount of hashes in rows and columns.
This is also listed in the instructions above

2021-05-18 05:38 UTC, ry-oc commented on content/projects/katas/level-1/_index.md
> +- All 3 sides of the triangle should the same amount as the input.
Some of these are also repeats

2021-05-18 05:38 UTC, ry-oc commented on content/projects/katas/level-1/_index.md
> +- Ensure that an **array of strings** is being passed as an argument.
This line is a repeat

2021-05-18 05:38 UTC, ry-oc commented on content/projects/katas/level-1/_index.md
> +- Ensure that two arrays are being passed as arguments.
remove the repeated instructions.

2021-05-25 07:03 UTC, ry-oc requested changes
Some small things

2021-05-25 07:03 UTC, ry-oc commented on content/projects/katas/level-1/_index.md
> +**Task 1.4 and Task 1.5** is pretty straight forward.
Does this line serve a purpose or provide any additional info?

2021-05-25 07:03 UTC, ry-oc commented on content/projects/katas/level-1/_index.md
> +- Check if a specific task wants an output to be returned, if so the **return** keyword should be used to stop the execution of the function.
RE: 184, 185, & 186
Does this even need to be said at all? I think this is in the project instructions above as well? Things should be DRY

2021-05-31 07:21 UTC, ry-oc approved these changes
looks good to me

2021-06-02 05:40 UTC, sheenarbw approved these changes

2021-06-02 05:40 UTC, merged