problem solving material
Umuzi-org/ACN-syllabus pull request #176
Opened 2021-05-13 12:05 UTC by Sbonelo01

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x ] I ran the linter and there were no errors
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code

2021-05-18 05:14 UTC, ry-oc requested changes
Please can you also add this as a prerequisite of `Get started with hackerrank`

2021-05-18 06:52 UTC, Sbonelo01 commented
> Please can you also add this as a prerequisite of `Get started with hackerrank`

Alright cool

2021-05-24 07:58 UTC, ry-oc approved these changes
The prerequisite was added in a separate PR :)

2021-05-25 07:39 UTC, sheenarbw approved these changes

2021-05-25 07:39 UTC, merged