Ticket106
Umuzi-org/ACN-syllabus pull request #179
Opened 2021-05-18 08:00 UTC by AxelBankuna

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-05-20 04:44 UTC, ry-oc requested changes

2021-05-20 04:44 UTC, ry-oc commented on content/projects/memory-game/part-1/_index.md
> +- Check the good naming conventions are followed for variables, files, functions, classes and so on.
Review instructions should be project-specific, clean code guidelines should always be followed, therefore they don't need to be mentioned

2021-05-31 07:23 UTC, ry-oc approved these changes

2021-06-02 05:39 UTC, sheenarbw approved these changes

2021-06-02 05:39 UTC, merged