added tags for java projects
Umuzi-org/ACN-syllabus pull request #187
Opened 2021-05-25 13:27 UTC by Lisa1400

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-05-26 13:10 UTC, ry-oc requested changes
1 super small change

2021-05-26 13:10 UTC, ry-oc commented on content/projects/java-specific/introduction-to-spring-boot/part-3/_index.md
> +
Should this empty line be there?

2021-05-31 07:24 UTC, ry-oc approved these changes

2021-06-02 05:38 UTC, sheenarbw approved these changes

2021-06-02 05:38 UTC, merged