Added instructions for reviewer
Umuzi-org/ACN-syllabus pull request #189
Opened 2021-05-26 09:02 UTC by EckardBerry

Related issues: [please specify]

## Description:  Added instructions for a reviewer for the statistical thinking project.

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2021-06-02 03:27 UTC, ry-oc requested changes
Small thing: Just a language chage. Recruit to learner

2021-06-29 07:12 UTC, TheAbstract requested changes
@EckardBerry 8 and 9 are super NB, without question this always where the problems are, glad you included this👌🏾.
When referring to specific functions or code back-ticks (``) will render them just like in a notebook or here on GH; so instead of .groupby() it shows as `.groupby()`.

2021-06-29 07:12 UTC, TheAbstract commented on content/projects/data-science-specific/statistical-thinking/_index.md
> +   a dataset, things such as pd.set_option( ).
```suggestion
   a dataset, things such as `pd.set_option()`.
```

2021-06-29 07:12 UTC, TheAbstract commented on content/projects/data-science-specific/statistical-thinking/_index.md
> +   comfortable with what is presented to them by these commands.
```suggestion
3. Learners need to be able to make the correct deductions following commands such as `.info()` and `.describe()`. 
Sometimes learners will use these commands since they know it is required of them, but they are not entirely comfortable with what is presented to them by these commands.
```

2021-06-29 07:12 UTC, TheAbstract commented on content/projects/data-science-specific/statistical-thinking/_index.md
> +   numpy provides.
```suggestion
4. How do learners answer basic questions such as 'How many countries are represented'.  If it is a case of endless 'for' loops and 'if' statements then the recruit is not comfortable with the basic functionality which pandas or numpy provides.
```

2021-06-29 07:12 UTC, TheAbstract commented on content/projects/data-science-specific/statistical-thinking/_index.md
> +   bad practice.
There is some odd spacing going on where there are sentence brakes on new lines like 
> of the project. 

If it doesn't affect how `hugo` renders the text on the site then it doesn't matter much but its some thing you should check.
```suggestion
5. Does the learner clean the dataframe, impute missing values and set the dataframe in a neat order at the beginning of the project.  If not, the learner will continue to create sub-dataframes for each question to follow.  This is bad practice.
```

2021-06-29 07:12 UTC, TheAbstract commented on content/projects/data-science-specific/statistical-thinking/_index.md
> +   .contains( ), .groupby( ).  When learners don't understand how to use these functions as a collective they revert
```suggestion
   CO2 emissions in 1990, and what are their emissions' using standard pandas functionality such as `.nlargest()`,
   `.contains()`, `.groupby()`.  When learners don't understand how to use these functions as a collective they revert
```

2021-07-16 11:36 UTC, TheAbstract approved these changes

2021-07-28 13:02 UTC, ry-oc approved these changes

2021-08-05 05:58 UTC, merged