Issue 83
Umuzi-org/ACN-syllabus pull request #196
Opened 2021-05-31 20:07 UTC by TheAbstract

Related issues: [#83]

## Description:

What are you up to? Fill us in :)
Added instructions for reviewer

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2021-06-22 08:16 UTC, ry-oc commented
@TheAbstract , @Andy-Nkumane or @EckardBerry should probably be the first reviewer on this

2021-06-25 07:14 UTC, EckardBerry requested changes
Hello

Just one comment, should 'build' in line 85 not be 'built'?

2021-06-29 06:23 UTC, TheAbstract commented on content/projects/data-science-specific/cross-validation-and-simple-linear-regression/_index.md
> +3. When fitting the model to the test data, make sure that a new model isn't being build. There should only be one model in the notebook.
```suggestion
3. When fitting the model to the test data, make sure that a new model isn't being built. There should only be one model in the notebook.
```

2021-07-01 11:05 UTC, EckardBerry approved these changes

2021-07-14 04:24 UTC, ry-oc approved these changes

2021-08-05 06:06 UTC, merged