morse code: cater for all special characters
Umuzi-org/ACN-syllabus pull request #203
Opened 2021-06-03 08:48 UTC by AxelBankuna

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-06-07 05:19 UTC, ry-oc approved these changes

2021-06-07 05:50 UTC, sheenarbw requested changes
some repeated stuff can be removed.

2021-06-07 05:50 UTC, sheenarbw commented on content/projects/morse-code/_index.md
> +- https://morsecode.world/international/translator.html
Why do we need 2 translators? Rather just use the best one and remove the other link.

2021-06-22 09:10 UTC, sheenarbw approved these changes

2021-06-22 09:10 UTC, merged