instructions added
Umuzi-org/ACN-syllabus pull request #207
Opened 2021-06-08 07:09 UTC by Sbonelo01

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2021-06-08 07:48 UTC, kaleem99 requested changes
nice work, but on line 216 pls your grammar is not correct.
"Ensure that the add function the takes a string as an argument."
should be "Ensure that the add function takes a string as an argument."
pls, use Grammarly before pushing.

2021-06-08 08:07 UTC, Sbonelo01 commented
> nice work, but on line 216 pls your grammar is not correct.
> "Ensure that the add function the takes a string as an argument."
> should be "Ensure that the add function takes a string as an argument."
> pls, use Grammarly before pushing.

Howzit @kaleem99 , There is no Line 216 on this PR. There is also no `add function`

2021-06-08 14:58 UTC, kaleem99 requested changes
sorry for the previous review I looked at the wrong file. your instructions looks good but there are a few spelling mistakes like line 91 you incorrectly spelled the word available, pls use Grammarly to check for these small issues. other than that everything else looks good.

2021-06-09 12:21 UTC, kaleem99 approved these changes
instruction looks good.

2021-06-28 08:26 UTC, AxelBankuna requested changes
`The fs module is readily available in Node.js, so there wont be any need to have node_modules in the repo.` : Besides the reason stated above, node_modules should not be in repo.

`The load function should print/consol.log the visitor data. ensure that the visitor data is not returned instead.`: typo "consol".

2021-07-01 11:39 UTC, AxelBankuna commented on content/projects/nodejs/file-io/_index.md
> +- The use of string literals is highly encouraged for the save method. It's good if a recruit uses them
This seems more of a tip for the person doing the project than it is for the reviewer.

2021-07-01 11:39 UTC, AxelBankuna commented on content/projects/nodejs/file-io/_index.md
> +- The load function should print/console.log the visitor data. ensure that the visitor data is not returned instead.
Start new sentence with uppercase letter.

2021-07-06 06:43 UTC, AxelBankuna approved these changes

2021-08-05 06:33 UTC, sheenarbw requested changes
Please use the word "learner" instead of recruit.

This content is used by other code schools, so we ned language that makes sense there. 
And when we work with employed learnerships, such as Telkom, the word "recruit" doesn't apply

2021-09-08 14:21 UTC, sheenarbw requested changes
Please dont use the word "recruit". Rather say "learner".

2021-09-08 14:26 UTC, sheenarbw requested changes

2021-09-08 14:26 UTC, sheenarbw commented on content/projects/nodejs/file-io/_index.md
> +- The save method should save the data in lower case and whitespace should be replaced by an underscore. This is the only accepted format.
You mean the file name should be lowercase?

2021-09-08 14:26 UTC, sheenarbw commented on content/projects/nodejs/file-io/_index.md
> +- Edge cases should be catered for. The recruit should make sure that the load function takes in the proper data type.
please say learner not recruit

2021-09-27 10:39 UTC, sheenarbw requested changes

2021-09-27 10:39 UTC, sheenarbw commented on content/projects/nodejs/file-io/_index.md
> +- The load function should print/console.log the visitor data. Ensure that the visitor data is not returned instead. UNLESS, the learner has taken up the challenge on laid out in the instructions sec
Consider rewording your firsdt point. The english delicious is :P 

Maybe "taken on the challenge laid out..."

2021-09-27 10:39 UTC, sheenarbw commented on content/projects/nodejs/file-io/_index.md
> +- The learner should use mocks and spies if/when testing this project - since the project requires interacting with the file system.
Please add something about DRY code. People consistently write repetitive code when figuring out the file names. If they have repeated logic then that's bad.

2021-10-11 10:48 UTC, sheenarbw approved these changes
Some changes

2021-10-11 10:48 UTC, sheenarbw commented on content/projects/nodejs/file-io/_index.md
> + > Imagine that the code produced by the learner needs to be maintained, imagine that some parts of the code will have to change over time. Ideally, changes to the code should be made just once, and
Why different formatting here?

2021-10-11 10:49 UTC, merged