instructions for reviewer: Animals part1 #107
Umuzi-org/ACN-syllabus pull request #216
Opened 2021-06-28 13:54 UTC by AxelBankuna

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-07-06 12:16 UTC, Andy-Nkumane requested changes

2021-07-06 12:16 UTC, Andy-Nkumane commented on content/projects/oop/animals/part1/_index.md
> +- A constructor that accepts a string to set the name for constructed pet  should exist.
```suggestion
- A constructor that accepts a string to set the name for the constructed pet should exist.
```

2021-07-28 13:48 UTC, ry-oc approved these changes

2021-08-05 06:27 UTC, sheenarbw approved these changes

2021-08-05 06:28 UTC, merged