added dom maipulation tests links
Umuzi-org/ACN-syllabus pull request #236
Opened 2021-09-09 06:19 UTC by kaleem99

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-09-13 09:49 UTC, Sbonelo01 approved these changes

2021-09-27 10:55 UTC, sheenarbw requested changes

2021-09-27 10:55 UTC, sheenarbw commented on content/projects/semitone-challenge/gui-part-1/_index.md
> +let notesDiv = document.getElementById("displayNotes").innerHTML;
let versus const is something that comes up all the time when I am reviewing code. 

Should these be consts?

2021-10-11 10:52 UTC, sheenarbw requested changes
same as before

2021-10-11 10:52 UTC, closed without merging