Employed boot syllabuses
Umuzi-org/ACN-syllabus pull request #242
Opened 2021-09-15 04:45 UTC by ry-oc

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-09-15 07:10 UTC, sheenarbw requested changes
There aer a few odd things. Mostly your thinking around where to put Git in doesn't make all the sense.

Here is the order I'm thinking: 

1. Intro to tilde part 1: This should get folks to be able to submit links 

2. Skills test: 
- People need to know just enough about github that they can create a repo and drag-drop upload files 
- Link submission to project 

3. Intro to tilde part 2 

4. Get everyone to do the git excercises now. We dont need command line git, or git installation instructions before this point

5. Further coding content. However we can probably just skip this completely, if someone is in then we just add a full on syllabus to their board. The git excercises will keep people busy enough.

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-data-eng-post-skills-test.md
> +- {{% contentlink path="projects/katas/level-1" flavour="python" %}}
Don't worry about "post" stuff for now. I wouldn't make this the post stuff anyway. We do still need to do git after katas 0.

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-data-eng-skills-test.md
> +- {{% contentlink path="topics/clean-code/python" %}}
can leave out clean code. I think most folks rush through it in bootcamp anyway. We can put it after boot

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-data-eng-skills-test.md
> +- {{% contentlink path="projects/katas/level-0" flavour="python" %}}
Just because they are linking to a repo, does not mean that they need to use git from the command line at this point. We can probably skip the git commands for now. 

If people know how to make a git repo and upload code there, then send us a link to their repo, that should be enough for katas 0, right?

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-common-tech-requirements.md
> +- {{% contentlink path="environment-setup/git" %}}
I dont think we need this initially. What is this for?

We'll be trying to reduce reliance on git initially, right? Just focusiong on code katas. This will distract folks I think

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-data-sci-skills-test.md
> +- {{% contentlink path="topics/bootcamp/git-for-bootcamp" %}} TODO:  recreate with examples & video on how to submit - drag and drop files
clean code and git can be left out

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-intro-to-tilde-for-skills-test.md
> +title: Employed intro to Tilde for skills test
consider rewording title so it's english. How about:

Intro to Tilde for employed learner skills test.

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-intro-to-tilde-for-skills-test.md
> +- {{% contentlink path="topics/bootcamp/success-in-bootcamp" %}} TODO: Create intro to skills test?
If time runs out, I'd skip the "success in" stuff. These folks are meant to be professionals and they would have been told that their understanding would be assessed.

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-intro-to-tilde-post-skills-test.md
> +title: Employed intro to Tilde for post skills test
consited rewording.

Maybe even: 

Employed learnership intro to Tilde: part 2.

The words are just a bit funny

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-intro-to-tilde-post-skills-test.md
> +- {{% contentlink path="projects/tilde/link-card-tutorial" flavour=""%}}
They probably need the link tutrial first since they'll be linking us to things as part of their skills test.

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-java-post-skills-test.md
> +- {{% contentlink path="projects/katas/level-0" flavour="java" %}}
post means after... are you saying that the level 0 katas will happen after the skills test? Aren't those the ACTUAL skills test?

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-java-skills-test.md
> +- {{% contentlink path="projects/katas/level-1" flavour="java" %}}
This looks way too hard. Should just be katas 0.

I thin you swapped the files around. 

Post skills test technical content : We need folks to nail git next, then continue with code

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-web-dev-post-skills-test.md
> +- {{% contentlink path="projects/katas/level-1" flavour="javascript" %}}
Git excercises and not a lot else please

2021-09-15 07:10 UTC, sheenarbw commented on content/syllabuses/employed-web-dev-skills-test.md
> +- {{% contentlink path="topics/clean-code/java-script" %}}
leave out git and clean code.

2021-09-15 11:39 UTC, ry-oc commented on content/syllabuses/employed-common-tech-requirements.md
> +- {{% contentlink path="environment-setup/git" %}}
This is to come after the initial skills test and contains git and git stuff if they need more to do

2021-09-20 10:35 UTC, sheenarbw requested changes

2021-09-20 10:35 UTC, sheenarbw commented on content/employed-skills-tests/bootcamp-exploratory-data-analysis/_index.md
> +You can find the instructions, relevant files etc. here: {{% contentlink path="projects/data-science-specific/bootcamp-exploratory-data-analysis" flavour="python" %}}
I think maybe we need a little bit more info.

Please create a github repo and then blah blah etc
Pleae submit a link to .... The url should look something like https://whatevs"

Also, I just thought of this: How can we make sure that future bootcampers can't find and copy the work from these repos? We had a lot of trouble because the Nobel prize stuff was so very copyable.

Tricky...

2021-09-20 10:35 UTC, sheenarbw commented on content/syllabuses/employed-intro-to-tilde-for-skills-test.md
> +title: Employed learnership intro to Tilde part 1
Do the file names make sense? Or do the titles make sense? It might be good to take the most sensible naming convention and then use it for both. 

Do you want to keep `employed intro to tilde for skills test`?

2021-09-22 01:58 UTC, ry-oc commented on content/employed-skills-tests/bootcamp-exploratory-data-analysis/_index.md
> +You can find the instructions, relevant files etc. here: {{% contentlink path="projects/data-science-specific/bootcamp-exploratory-data-analysis" flavour="python" %}}
Yeah, my thoughts is when they go from the skills test to the full program they will need to port their code to their umuzi repos and they will need to delete these repos, what are your thoughts?

It creates some manual checking work but its the best solution I can think of at the moment

2021-09-22 16:15 UTC, sheenarbw approved these changes

2021-09-22 16:16 UTC, merged