added reviewers Instructions morse code
Umuzi-org/ACN-syllabus pull request #246
Opened 2021-09-22 11:08 UTC by kaleem99

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-09-23 06:36 UTC, EckardBerry requested changes
Hello

Just want to make sure, when you say a "Global object" is used for alphabet characters, numbers etc.  I see most people declare a global constant, is it different when you do this in JS?  Do you declare a global object or a global constant in JS?

This will have an influence on a recruits' understanding if it is different for Java, Python and JS.

2021-09-23 06:41 UTC, kaleem99 commented
Global object but it should be of const type, should change the wording to global constant.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: Thursday, 23 September 2021 08:36 AM
To: ***@***.***>
Cc: Kaleem ***@***.***>; ***@***.***>
Subject: Re: [Umuzi-org/ACN-syllabus] added reviewers Instructions morse code (#246)


@EckardBerry requested changes on this pull request.

Hello

Just want to make sure, when you say a "Global object" is used for alphabet characters, numbers etc. I see most people declare a global constant, is it different when you do this in JS? Do you declare a global object or a global constant in JS?

This will have an influence on a recruits' understanding if it is different for Java, Python and JS.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/Umuzi-org/ACN-syllabus/pull/246#pullrequestreview-761632974>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AO3LXGHZL3YSFKBTSH2BFZLUDLDIJANCNFSM5ERBVHMQ>.
Triage notifications on the go with GitHub Mobile for iOS<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.

2021-09-23 06:56 UTC, AxelBankuna commented on content/projects/morse-code/_index.md
> +- An assertion function was used to assert if both functions input and output data are the same
We've been requesting this as a compulsory requirement. Do we now consider this use of an assert function as optional?

2021-09-27 11:08 UTC, sheenarbw requested changes
A few small things and one big thing

2021-09-27 11:08 UTC, sheenarbw commented on content/projects/morse-code/_index.md
> +  - topics/intro-to-assertive-programming
This is now a broken link.

If I ask you to open a file named "intro-to-assertive-programming" and yet the file doesn't exist then you wont be able to open the file.
If you update a link anywhere then you need to make sure it points to something that exists
If you change a file path then you need to make sure that everything that refers to that file is updated with the new path

This stuff is connected.

2021-09-27 11:08 UTC, sheenarbw commented on content/projects/morse-code/_index.md
> +- Ensure that the lettersToMorseCode function can convert numbers, special characters and alphabets to morseCode and the morseCodeToLetters function can convert morse code to numbers, alphabets and s
rather say ...numbers, special characters and letters of the alphabet.
An alphabet is something that contains a lot of different letters. 

Also look over capitalisation.

And inline code can be surrounded by single backtickls to make it appear as code. Eg `lettersToMorseCode`

2021-09-27 11:08 UTC, sheenarbw commented on content/projects/morse-code/_index.md
> +- Make sure that both functions returns and not prints the output.
Make sure that both functions return the output. Neither function should print the output

2021-09-27 11:08 UTC, sheenarbw commented on content/projects/morse-code/_index.md
> +- Make sure a global constant was used to contain all the data e.g alphabets, numbers, special characters and morse code.
letters of the alphabet

2021-09-29 16:04 UTC, AxelBankuna commented on content/projects/morse-code/_index.md
> +- Make sure an assertion function was used to assert if both functions input and output data are the same
Missing full-stop at the end of this sentence.

2021-09-30 12:58 UTC, AxelBankuna approved these changes

2021-09-30 16:19 UTC, Sbonelo01 approved these changes
LGTM

2021-10-11 10:54 UTC, sheenarbw approved these changes

2021-10-11 10:54 UTC, merged