shop database project content updated
Umuzi-org/ACN-syllabus pull request #247
Opened 2021-09-22 17:11 UTC by Babalwa01

Related issues: [please specify]
Added content for the Shop database project to specify how the structure of the project repository should look like.

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2021-09-23 08:36 UTC, Sbonelo01 commented
Hey @Babalwa01 , Is this PR linked to a specific issue? otherwise, I'm not sure what criteria I should review it against

2021-09-23 08:46 UTC, Babalwa01 commented
> Hey @Babalwa01 , Is this PR linked to a specific issue? otherwise, I'm not sure what criteria I should review it against

Hey @Sbonelo01 There isn't an issue yet. I have come across many instances where recruits put all the Sql commands in one file, name it _shopDatabase.sql_ and some of the repos don't have a _.yml_ file. I have based it on the reviews I received from you earlier when I did my shop database project

2021-09-23 08:56 UTC, Sbonelo01 requested changes

2021-09-23 08:56 UTC, Sbonelo01 commented on content/sql/shop-project/_index.md
> +when the reviewer is looking for the commands you used for creating the database they should be able to navigate to a file named **create-database.sql**  , navigate to a file named **create-tables.sq
This is good to point out. Can you please make this in bullet or list form? Just so it is clearer

2021-09-27 09:30 UTC, Sbonelo01 approved these changes
LGTM

2021-09-27 10:59 UTC, sheenarbw approved these changes

2021-09-27 10:59 UTC, merged