Updated instructions for the reviewer: memory-game part-2
Umuzi-org/ACN-syllabus pull request #252
Opened 2021-10-04 09:19 UTC by Ngoakor12

Related issues: [please specify]

## Description:
Removed the instruction `Make sure that cards can not be clicked once the timer has run out` because the according to the timer feature description, the timer is for checking how long it takes to finish the game. It's not a countdown timer so it won't "run out".
What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-10-11 10:58 UTC, sheenarbw requested changes
I'm not sure about this one. Why remove that requirement?

2021-10-11 10:58 UTC, sheenarbw commented on content/projects/memory-game/part-2/_index.md
> -- Make sure that cards can not be clicked once the timer has run out.
Why did you remove this? Surely once the timer is finished the game is over?

2021-10-11 11:54 UTC, Ngoakor12 commented on content/projects/memory-game/part-2/_index.md
> -- Make sure that cards can not be clicked once the timer has run out.
I edited the point instead of removing it.

My confusion was around how the timer would be finished if it's counting up and measuring the time elapsed like the feature instruction suggests.

2021-10-25 08:25 UTC, sheenarbw approved these changes

2021-10-25 08:25 UTC, merged