Sql naming convention topic
Umuzi-org/ACN-syllabus pull request #257
Opened 2021-10-12 06:23 UTC by Babalwa01

Related issues: [https://github.com/Umuzi-org/ACN-syllabus/issues/229]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2021-10-12 06:26 UTC, babalwa-mbolekwa commented
May you please kindly review, I haven't yet added an id and haven't added the topic to other projects as I needed to check if I was doing the work correctly first and if there are any changes requested before I can add it to other SQL projects. Thanks.

2021-10-12 09:29 UTC, kaleem99 requested changes
looks good but just one thing needs to be changed, line 13 previously is spelt incorrectly.

2021-10-13 09:38 UTC, vmonoge approved these changes

2021-10-13 09:39 UTC, vmonoge commented
The spelling error was corrected

2021-10-18 14:28 UTC, kaleem99 approved these changes

2021-10-25 08:26 UTC, sheenarbw requested changes

2021-10-25 08:26 UTC, sheenarbw commented on content/topics/clean-code/sql/_index.md
> +_db_id:
please remove this line

2021-10-25 08:26 UTC, sheenarbw commented on content/topics/clean-code/sql/_index.md
> +**SQL (Structured Query Language)** is mostly used to manipulate data from a relational database. A database is a container to help organize data and efficiently store and retrieve data. **Relational
container might be the wrong name. If you google `sql container` or `database container` then all sorts of funny things come up.

2021-10-25 08:26 UTC, sheenarbw commented on content/topics/clean-code/sql/_index.md
> +- Foreign key column: Use the specific table's name and a "id" e.g. `customer_id` - that way it easily references the foreign key to the `customer` table
This is great! 

Can you add an example? Maybe a picture.

2021-11-15 22:24 UTC, Sbonelo01 approved these changes

2021-11-23 03:25 UTC, ry-oc approved these changes
changes done :)

2021-11-23 07:53 UTC, sheenarbw approved these changes

2021-11-23 07:53 UTC, merged