learning outcomes
Umuzi-org/ACN-syllabus pull request #266
Opened 2021-10-19 11:59 UTC by Sbonelo01

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

@sheenarbw and @TheAbstract , please note that I have closed the previous similar PR due to some git issues.

2021-10-19 14:03 UTC, sheenarbw requested changes

2021-10-19 14:03 UTC, sheenarbw commented on learning_outcomes.yaml
> +<<<<<<< HEAD
This is a merge conflict.  Please fix

2021-10-19 15:55 UTC, TheAbstract approved these changes

2021-10-20 06:16 UTC, sheenarbw approved these changes

2021-10-20 09:31 UTC, merged