added instructions for JavaScript using jasmine to project
Umuzi-org/ACN-syllabus pull request #277
Opened 2021-12-03 13:57 UTC by Steve-code16

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2021-12-13 10:00 UTC, ry-oc requested changes
Looks good, but there was some spacing added automatically that needs to be corrected.

Thanks for your contribution

2021-12-13 10:00 UTC, ry-oc commented on content/projects/oop/animals/part2/_index.md
> +  - any_language
please can you remove the added spaces in the front matter?

2021-12-13 10:00 UTC, ry-oc commented on content/projects/oop/animals/part2/_index.md
> +    - projects/oop/animals/part1
please can you remove the added spaces in the front matter?

2021-12-13 10:00 UTC, ry-oc commented on content/projects/oop/animals/part2/_index.md
> +  - oop
please can you remove the added spaces in the front matter?

2022-01-17 06:11 UTC, Vuyisanani approved these changes

2022-01-19 11:54 UTC, sheenarbw approved these changes

2022-01-19 11:54 UTC, merged