Password checker update
Umuzi-org/ACN-syllabus pull request #278
Opened 2021-12-06 13:34 UTC by TheAbstract

Related issues: NONE

## Description:

Removing reference to old `password id valid` function. Updated reviewers instructions.

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2021-12-14 07:14 UTC, EckardBerry approved these changes

2022-01-11 13:52 UTC, sheenarbw requested changes
Mostly good. Just inconsistent naming conventions in the js stuff

2022-01-11 13:52 UTC, sheenarbw commented on content/projects/tdd/password-checker/part1/_index.md
> +        - password_strength.js
Should this not have _spec like the others? Why should the naming convention be different now?

2022-01-12 13:33 UTC, Andy-Nkumane requested changes
here is something that is missed:
* looking at the error/exception message for the password is valid, the second condition has an extra `than` - `password should be longer than than 8 characters`

2022-01-13 06:42 UTC, Andy-Nkumane approved these changes

2022-01-19 11:57 UTC, sheenarbw approved these changes

2022-01-19 11:57 UTC, merged