issue #253 (draft): move intro-do-data-ethics
Umuzi-org/ACN-syllabus pull request #279
Opened 2021-12-09 18:46 UTC by MondeAnna

Related issues: [#253 ]

## Description:

- Move the intro-to-data-ethics content directory from `workspace` to `topics`
- `frontmatter`: removal of `pre` mapping, to ensure that link is rendered in keeping with the rest of the code

## Why This is a Draft

- The linked content has a few errors, some examples:
    - [Spelling](https://docs.google.com/presentation/d/e/2PACX-1vRDfP548V2pm9s3XYS3HjV5zmFoxb3gqLHCUVQI5g00VefSOD5MxgTCe-Q9htK1Cw/embed?start=false&loop=false&delayms=3000&slide=id.p2)
    - [Formatting](https://docs.google.com/presentation/d/e/2PACX-1vRDfP548V2pm9s3XYS3HjV5zmFoxb3gqLHCUVQI5g00VefSOD5MxgTCe-Q9htK1Cw/embed?start=false&loop=false&delayms=3000&slide=id.p10)
- Lastly, the linked content is dated to 2019 and I am uncertain that it will be getting fixed

## I solemnly swear that:

- [X] I ran the hugo server and looked at my changed in the browser with my own eyes
- [X] I ran the linter and there were no errors
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code

2021-12-13 10:02 UTC, ry-oc approved these changes

2021-12-15 06:25 UTC, ry-oc commented
Please be careful with the branching strategy, at Umuzi we use feature branching meaning changes or fixes should be separated into their own branches & PRs.

The changes you made here to the skills assessments have already been made and merged in another branch. If you pull and merge develop this should be good to merge

2021-12-15 06:51 UTC, MondeAnna commented
Thanks for the heads up. Managed to pull from develop and all looks resolved

2022-01-14 11:33 UTC, TheAbstract requested changes
@MondeAnna this is almost there, just one thing. The content type needs to be changed in the headers of the file; `content_type: workshop` -> `content_type: topic`.

2022-01-18 15:52 UTC, TheAbstract approved these changes

2022-01-18 18:23 UTC, Vuyisanani approved these changes

2022-01-19 11:52 UTC, sheenarbw approved these changes

2022-01-19 11:52 UTC, merged