syllabus (proposal): code review culture
Umuzi-org/ACN-syllabus pull request #283
Opened 2021-12-15 12:28 UTC by MondeAnna

## Description:

Greetings all.

<br />

This is a follow up to a discussion with Ryan about alternate ways that recruits could be taught to review each other.

<br />

The primary lessons being:
1. How to decide which part of a review is important
2. How to be tactful during a critique of another's work

<br />

## Reviewers

Stage one has the recruit in the role of the reviewer:

<br />

[The Graceful Reviewer.](https://www.youtube.com/watch?v=XY6eA2_2hOg) Teaches tact and decernment.
[Seed the Culture You Desire.](https://www.youtube.com/watch?v=xT3oFHBDEZY) Discusses the long term benefits of being a graceful reviewer.

<br />

## PR Author

<br />

Stage two has the recruit in the roles of both author and reviewer: [The emphasis is on the learning and teaching aspects of code reviews.](https://www.youtube.com/watch?v=PJjmw9TRB7s)

<br />

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-01-17 06:50 UTC, sheenarbw requested changes
Some punctuation and capitalisation best practices.

2022-01-17 06:50 UTC, sheenarbw commented on content/topics/code-reviews/part-1-reviewers/_index.md
> +The people who's code you review, are people. Remember this. Treat them with respect.
Three is an extra ,

`The people who's code you review, are people` should be `The people who's code you review are people`

2022-01-17 06:50 UTC, sheenarbw commented on content/topics/code-reviews/part-1-reviewers/_index.md
> +- Lesson 1: [The Graceful Reviewer](https://www.youtube.com/watch?v=XY6eA2_2hOg)
`The graceful reviewer` is better than Title Case. Title Case is even bad for titles. Just treat english as sentences

2022-01-17 06:50 UTC, sheenarbw commented on content/topics/code-reviews/part-2-author/_index.md
> +- [Both Author and Review Pull Requests](https://www.youtube.com/watch?v=PJjmw9TRB7s)
Same thing with normal english versus title case

2022-01-17 11:30 UTC, MondeAnna commented
Afternoon Sheena

Now that the capitalisation is mentioned, I can see it everywhere.

2022-02-03 04:22 UTC, ry-oc approved these changes
Changes done

2022-02-03 06:24 UTC, sheenarbw approved these changes

2022-02-03 06:25 UTC, merged