added instructions for reviewer - animals part 2
Umuzi-org/ACN-syllabus pull request #289
Opened 2022-01-25 05:31 UTC by Andy-Nkumane

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-01-28 04:56 UTC, Vuyisanani approved these changes

2022-01-28 09:12 UTC, TheAbstract requested changes
Remember that this project is shared across languages so the instructions need to be general enough to make sense for everyone. Maybe ask one js/java person to see if these make sense and don't cause any confusion.

2022-01-28 09:12 UTC, TheAbstract commented on content/projects/oop/animals/part2/_index.md
> +- There should be no global variable.
```suggestion
- There should be no global variables.
```

2022-01-28 09:12 UTC, TheAbstract commented on content/projects/oop/animals/part2/_index.md
> +- `self` should not be overused, if a variable is only used in one place then it is not necessary to use `self`.
I don't think the issue here is the number of times the variable is used but how. If a variable is only used within a given method then constantly referring to it as `self.variable` isn't necessary.

2022-02-02 09:37 UTC, Sbonelo01 reviewed
A point you could try to emphasize is on this information:

`//Dog Tests`
`Test -> Does dog eat Food should Pass`
`Test -> Does dog eat food should Fail`
`//Cat Tests`
`Cat cat = new Cat();`
`Test -> Does cat Bark should Fail`
`Test -> Does cat Meow should Pass`
`Test -> Does cat eat meat should Fail`
`Test -> Does cat eat Food should Pass`
`Test -> Does cat eat food should Fail`

2022-02-02 09:37 UTC, Sbonelo01 commented on content/projects/oop/animals/part2/_index.md
> +- `Dog` and `Cat` class `sounds()` should return their respective sounds "Bark" and "Meow".
This feels like a repetition of what's already in the instructions

2022-02-02 15:02 UTC, TheAbstract approved these changes

2022-02-02 15:02 UTC, TheAbstract commented on content/projects/oop/animals/part2/_index.md
> +- `Dog` and `Cat` class `sounds()` should return their respective sounds "Bark" and "Meow".
True but I've seen people mess this up, they either use the Animals `sounds` method or do some other odd thing. Doest hurt emphasising it.

2022-02-03 06:23 UTC, sheenarbw approved these changes

2022-02-03 06:23 UTC, merged