initial commit and some content
Umuzi-org/ACN-syllabus pull request #389
Opened 2022-03-18 15:36 UTC by kaleem99

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-03-22 12:41 UTC, FaithMo requested changes

2022-03-22 12:41 UTC, FaithMo commented on content/topics/web-frontend/react/redux-architecture/_index.md
> +Redux is a very powerful state management library used in JavaScript apps to mange the data of your application and was originally designed for react. Redux helps you write applications that behave c
Looks good, just fix the sentence structure. e.g
"..in Javascript apps to manage the data of an application, and was originally designed for React..."
and
"Redux helps you write applications that behave consistently by facilitating and sharing data across the components of an application..."

2022-03-24 06:36 UTC, FaithMo approved these changes

2022-03-28 22:22 UTC, Babalwa01 approved these changes

2022-03-31 05:52 UTC, ry-oc approved these changes

2022-04-04 06:34 UTC, sheenarbw requested changes
This PR adds content to the redux architecture topiuc that has very little to do with redux architecture.

It also doesn't follow the style gude because heading levels are skipped.

2022-04-04 06:34 UTC, sheenarbw commented on content/topics/web-frontend/react/redux-architecture/_index.md
> +### Fundamental principles
This should be a level 2 heading.

2022-04-04 06:34 UTC, sheenarbw commented on content/topics/web-frontend/react/redux-architecture/_index.md
> +### Fundamental principles
And I dont think you are actually covering any architectural guidelines here...

If you have content that should be added to topics/redux-intro/ then it should go there, not here. 

Eg getting started with redux is definately introductiory material. It has little to do with scalable architectures. Same can be said for "thinking in redux"

2022-05-31 06:29 UTC, ry-oc commented
No longer relevant

2022-05-31 06:29 UTC, closed without merging