Copy edit develop/content/specific skill success criteria/basic data analysis
Umuzi-org/ACN-syllabus pull request #394
Opened 2022-03-29 08:07 UTC by Faancy

Related issues: Copy Edit

## Description: Copy edit develop/content/specific skill success criteria/basic data analysis

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-03-29 09:31 UTC, Faancy commented
https://github.com/Umuzi-org/ACN-syllabus/pull/394

2022-03-29 14:12 UTC, FaithMo approved these changes

2022-03-30 04:32 UTC, JacobUmuzi requested changes
- Consistency is key. When referring to the die/dice, use the number name and make it a compound word. E.g. six-sided.
- line 74 remove the comma after 2

2022-03-30 20:55 UTC, JacobUmuzi approved these changes

2022-03-30 20:55 UTC, merged