Copy-edit-repo-project-tutorial-part2
Umuzi-org/ACN-syllabus pull request #395
Opened 2022-03-29 09:14 UTC by asradebe

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-03-29 21:09 UTC, JacobUmuzi requested changes
line 32 (new) maintain previous sentence, the word 'will' sounds a bit assertive on the familiarity. 'to complete is also correct as it refers to the complete column.

2022-03-30 06:23 UTC, asradebe commented
> line 32 (new) maintain previous sentence, the word 'will' sounds a bit assertive on the familiarity. 'to complete is also correct as it refers to the complete column.
Jacob those little changes were suggested by Grammarly. If we change it back to its original state then nothing will be changed on that card. I believe it should be good as it is. I used Sheena's styling guide to also help me. Can we maybe get a second opinion?

2022-03-30 06:43 UTC, ry-oc commented on content/projects/tilde/repo-card-tutorial/part-2/_index.md
> +## Move your card to the REVIEW column (AFTER YOUR PULL REQUEST IS MERGED! NOT BEFORE!)
this is a comment

2022-03-30 06:44 UTC, ry-oc requested changes

2022-03-30 06:44 UTC, ry-oc commented on content/projects/tilde/repo-card-tutorial/part-2/_index.md
> -This should feel very familiar. Do what it takes to get your card to complete.
this is acomment

2022-03-30 09:43 UTC, JacobUmuzi approved these changes

2022-03-30 09:45 UTC, merged