copy-edit-topic-into-git
Umuzi-org/ACN-syllabus pull request #449
Opened 2022-04-02 13:49 UTC by asradebe

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-04-04 14:15 UTC, JacobUmuzi requested changes

2022-04-04 14:15 UTC, JacobUmuzi commented on content/topics/git/_index.md
> +- make sure that you _push_ your latest work before the end of the business day **every day**
```suggestion
- make sure that you _push_ your latest work before logging off for the day **every day**
```

2022-04-04 14:36 UTC, asradebe commented
@JacobUmuzi I'm not sure what changes you want me to make here?

2022-04-05 04:14 UTC, JacobUmuzi approved these changes

2022-04-05 04:14 UTC, merged