copy-edit-problem-solving-technique
Umuzi-org/ACN-syllabus pull request #487
Opened 2022-04-04 10:45 UTC by asradebe

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-04-06 13:52 UTC, JacobUmuzi requested changes

2022-04-06 13:52 UTC, JacobUmuzi commented on content/language-agnostic/problem-solving-technique/_index.md
> +An edge case is kinda a funny thing to understand. You need to think of extreme values and see if your code can handle that.
```suggestion
An edge case is kind of a funny thing to understand. You need to think of extreme values and see if your code can handle that.
```

2022-04-06 13:52 UTC, JacobUmuzi commented on content/language-agnostic/problem-solving-technique/_index.md
> +- What if you need to do some processing on an input string and the string is empty? What if it's long?
```suggestion
- What if you need to do some processing on an input string and the string is empty? What if it's very long?
```

2022-04-06 13:52 UTC, JacobUmuzi commented on content/language-agnostic/problem-solving-technique/_index.md
> +Of course, reading about code and watching other people code is great. But if you want to get good at this stuff: Practice practice practice.
```suggestion
Of course, reading about code and watching other people code is great. But if you want to get good at this stuff: Practise practise practise.
```

2022-04-07 10:54 UTC, asradebe commented on content/language-agnostic/problem-solving-technique/_index.md
> +Of course, reading about code and watching other people code is great. But if you want to get good at this stuff: Practice practice practice.
Grammarly throws an error, lol lol

2022-04-07 10:55 UTC, asradebe commented on content/language-agnostic/problem-solving-technique/_index.md
> +- What if you need to do some processing on an input string and the string is empty? What if it's long?
grammarly throws an error here too

2022-04-12 04:26 UTC, JacobUmuzi approved these changes

2022-04-12 04:26 UTC, JacobUmuzi commented on content/language-agnostic/problem-solving-technique/_index.md
> +Of course, reading about code and watching other people code is great. But if you want to get good at this stuff: Practice practice practice.
```suggestion
Of course, reading about code and watching other people code is great. But if you want to get good at this stuff: Practise practise practise.
```

2022-04-12 04:27 UTC, merged