changed instructions
Umuzi-org/ACN-syllabus pull request #499
Opened 2022-04-04 17:01 UTC by kaleem99

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-04-05 06:22 UTC, sheenarbw requested changes
All the functions should take in the data array as an argument. Not just the `get customer baskets` function, ALL the functions.

2022-04-05 16:44 UTC, FaithMo requested changes

2022-04-05 16:44 UTC, FaithMo commented on content/projects/understanding-loops/_index.md
> +- All of your functions stated above should take in at least one argument, the data array, and should work with similar data.
i think maybe rephrase it to "All of the functions.." because these are notes to the reviewer, not the person who wrote the code

2022-04-06 10:27 UTC, FaithMo approved these changes

2022-04-14 10:51 UTC, Vuyisanani approved these changes

2022-04-19 06:09 UTC, sheenarbw requested changes
some grammer and inconsistency errors

2022-04-19 06:09 UTC, sheenarbw commented on content/projects/understanding-loops/_index.md
> +As with any kind of techie, data will be a part of your life. You're going to need to learn how to make this stuff dance.
techie is short for technical person (sortof). It's a noun. I am a techie. As a techie, I work with data.

Don't just hit things with the Grammarly hammer, make sure that sentences make sense.

2022-04-19 06:09 UTC, sheenarbw commented on content/projects/understanding-loops/_index.md
> +Write a function called `get customer baskets` that takes in an email address and the data array as an argument and returns a list/array of all the shopping baskets that belong to the customer with t
takes in the email address and the data array as arguments. There are 2 separate arguments

2022-04-19 06:09 UTC, sheenarbw commented on content/projects/understanding-loops/_index.md
> +- All the functions stated above should take in at least one argument, the data array, and should work with similar data.
This point starts with a capital letter. All the others are small letters. 
Should they all start with capital letters or should they all be small letters?

2022-04-19 07:39 UTC, Sbonelo01 approved these changes

2022-04-20 06:43 UTC, FaithMo approved these changes

2022-05-06 03:21 UTC, ry-oc approved these changes

2022-05-10 06:20 UTC, sheenarbw approved these changes

2022-05-10 06:22 UTC, sheenarbw commented
Merge conflicts

2022-05-16 08:50 UTC, ry-oc requested changes
one tiny thing missed

2022-05-16 08:50 UTC, ry-oc commented on content/projects/understanding-loops/_index.md
> +For example, if one customer paid for 2 hamsters and another customer paid for one hamster and a bag of sawdust then your function should return the following data structure:
There may be a missing colon on line 92, please check it out?

2022-05-18 09:22 UTC, ry-oc approved these changes

2022-05-24 06:02 UTC, sheenarbw approved these changes

2022-05-24 06:02 UTC, merged