updated instructions to match perfect projects
Umuzi-org/ACN-syllabus pull request #743
Opened 2022-04-20 11:20 UTC by kaleem99

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-04-26 05:06 UTC, Sbonelo01 approved these changes

2022-05-20 20:01 UTC, FaithMo approved these changes

2022-05-30 07:10 UTC, Vuyisanani approved these changes

2022-05-31 04:01 UTC, ry-oc requested changes
1 sentence should be revised to make it easier to read

2022-05-31 04:01 UTC, ry-oc commented on content/projects/oop/person/_index.md
> +1. **Multiple interests, commas, punctuation, and spacing** - Make sure that the interests array attribute can take in multiple interests and they all get printed out separated with a comma and space
Please revise the first sentence here, maybe break it down into more than one sentence, it is long and difficult to read.

2022-06-22 04:31 UTC, Sbonelo01 approved these changes

2022-06-23 14:02 UTC, FaithMo requested changes

2022-06-23 14:02 UTC, FaithMo commented on content/projects/oop/person/_index.md
> +   1 interest should look like this: `Hello, my name is Ryan, my gender is male and I am 30 years old. My interest is being a hardarse.`.
please remove the indentation here and on line 80

2022-06-24 07:52 UTC, FaithMo approved these changes

2022-06-27 20:20 UTC, Vuyisanani approved these changes

2022-07-06 10:54 UTC, sheenarbw requested changes
This doesn't fix the problem

If you look at the automarker config: The python tests and JS tests expect different things. 
1. The project instructions should state exactly what is requiered
2. the configuration should be consistent

Python
```
def test_no_interests():
    hanabi = Person("Hanabi", 31, "female", [])
    option1 = "Hello, my name is Hanabi, my gender is female and I am 31 years old. I have no interests."
    option2 = "Hello, my name is Hanabi, my gender is female and I am 31 years old."
    assert hanabi.hello() in [option1, option2]
``` 

JS
```
  it("should handle no interests and the hello method should include 'I have no interests'", () => {
    const person = new Person("Ryan", 30, "male");
    expect(person.hello()).toBe(
      "Hello, my name is Ryan, my gender is male and I am 30 years old. I have no interests."
    );
  });
```

2022-07-13 20:04 UTC, Sbonelo01 approved these changes

2022-07-14 06:19 UTC, FaithMo approved these changes

2022-07-18 14:22 UTC, KhalidUmuzi approved these changes

2022-07-21 06:23 UTC, ry-oc approved these changes

2022-07-26 13:12 UTC, sheenarbw approved these changes

2022-07-26 13:12 UTC, merged