new Contribution mechanism
Umuzi-org/ACN-syllabus pull request #75
Opened 2020-10-28 11:55 UTC by ToyaSims

Related issues: [please specify]

## Description:
this content doesn't have an issue, task was given during retro
What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2020-10-30 04:37 UTC, ry-oc commented on README.md
> +This video will walk you trough the whole process. Or you can just read the [docs](https://www.youtube.com/watch?v=j5-uaSgIGI0&feature=youtu.be).
Docs is linking to a video

2020-10-30 04:38 UTC, ry-oc commented on contribute.md
> +-experienced devs only
There should be a space for it to render correctly

2020-10-30 04:40 UTC, ry-oc commented on contribute.md
> +if an issue has the `status/issue-claimed` label please skip it and if you a beginner it is advisable to start with the issues that have the `good-first-issue` label. You can assign yourself an issue
Please change the discord link to an invite link not a channel link. You can use https://discord.gg/3jRwWPm

2020-10-30 04:42 UTC, ry-oc requested changes
See comments

2020-11-08 12:23 UTC, sheenarbw requested changes
Please finish this PR. There's feedback

2020-11-08 12:23 UTC, sheenarbw commented on README.md
> +This video will walk you trough the whole process. Or you can just read the [docs](https://www.youtube.com/watch?v=j5-uaSgIGI0&feature=youtu.be).
bump

2020-11-10 09:52 UTC, asradebe requested changes
Hi. Please attend to these requested changes by Friday so this can be merged. Please set up time on your calender to get this done

Thanks

2020-12-15 07:25 UTC, sheenarbw commented
Oi. Shall we close this PR or what?

2020-12-15 07:31 UTC, ToyaSims commented
No will work on it today

On Tue, 15 Dec 2020, 9:25 AM sheenarbw, <notifications@github.com> wrote:

> Oi. Shall we close this PR or what?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Umuzi-org/ACN-syllabus/pull/75#issuecomment-745107610>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALLLFOSCCFP25NHMRILBKA3SU4FQJANCNFSM4TCHAZWQ>
> .
>

2021-01-07 06:02 UTC, sheenarbw approved these changes

2021-01-07 06:02 UTC, merged