Basic data analysis part2
Umuzi-org/ACN-syllabus pull request #805
Opened 2022-05-30 12:13 UTC by TheAbstract

Related issues: https://github.com/Umuzi-org/Tilde/issues/447

## Description:

Replaced section on p-values with one on hypothesis testing. We should be putting emphasis on hypothesis test in general not on one particular aspect of it. The point isn't to just compute p-values but rather understand how to set up tests and when we accept a result as significant or not.

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-06-01 01:12 UTC, Andy-Nkumane approved these changes

2022-06-02 12:52 UTC, Samantha-Hampton approved these changes

2022-06-02 19:23 UTC, Rokhuda approved these changes

2022-06-07 06:33 UTC, ry-oc requested changes
Very minor change, or addition rather. Please add this to the relevant syllabuses

2022-06-08 14:07 UTC, TheAbstract commented
> Very minor change, or addition rather. Please add this to the relevant syllabuses

@ry-oc theres no need, this has already been done here https://github.com/Umuzi-org/ACN-syllabus/pull/797/files, and I branched of develop after this was merged.

2022-06-09 06:18 UTC, ry-oc approved these changes
My bad, didnt realise that was done

2022-06-14 11:41 UTC, sheenarbw approved these changes

2022-06-14 11:41 UTC, merged