added filenames
Umuzi-org/ACN-syllabus pull request #807
Opened 2022-05-31 19:42 UTC by FaithMo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-06-02 15:32 UTC, Ngoakor12 reviewed
Hey Faith, just have a few things.

- I think the placing of the environment section is in an odd place(top of the project before the project intro paragraphs), would the section coming before "Write some functionality" section not be slightly better for the flow of the project?
- The project instructions says to add the `data.json` file to your repo, so maybe add it in the src folder too?
- The project instructions mention nothing about tests nor do the tags mention it anywhere, If they are not required, the jasmine stuff might not be necessary. If they are, I think the tags or instructions should mention it somewhere.

Side note: I have completed this project on my own without being reviewed so take my suggestions with a pinch of salt as I'm not sure.

2022-06-03 06:05 UTC, FaithMo commented
Hey, yeah I forgot the project doesn't need the tests. 
I followed how other projects are set up, they put the file and directory naming at the top of the page.

2022-06-03 08:02 UTC, Ngoakor12 requested changes
The placing of the section is okay if it's consistent with other projects.

2022-06-03 08:02 UTC, Ngoakor12 commented on content/projects/understanding-loops/_index.md
> +   - package.json
Is the package.json required if there are no packages to install?

2022-06-05 19:57 UTC, FaithMo commented
Hi @Ngoakor12 , I have actually removed the data.json file because when i take a close look at the instructions, they say that the learner's code needs to work for data that has a similar structure to data.json, so that means they do not need to have the exact same database but that is similar, so we do not need to specify data.json in the directory.

2022-06-06 11:59 UTC, Ngoakor12 approved these changes
looks good to me

2022-06-06 21:50 UTC, Sbonelo01 approved these changes

2022-06-07 17:57 UTC, Vuyisanani approved these changes

2022-06-09 06:06 UTC, ry-oc approved these changes
looks fine

2022-06-14 11:04 UTC, sheenarbw approved these changes

2022-06-14 11:04 UTC, merged