Split string calculator into part 1 and part 2
Umuzi-org/ACN-syllabus pull request #812
Opened 2022-06-07 17:39 UTC by TheAbstract

Related issues: https://github.com/Umuzi-org/Tilde/issues/435

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-06-08 04:05 UTC, Andy-Nkumane requested changes
getting there:
* `Modify the add function so that it can support delimiters of any length` is present in both parts, it should only be in one part

2022-06-10 05:36 UTC, Andy-Nkumane approved these changes

2022-06-13 08:44 UTC, ry-oc approved these changes
Looks good to me :)

2022-06-13 12:05 UTC, Vuyisanani approved these changes

2022-06-14 11:07 UTC, sheenarbw approved these changes

2022-06-14 11:07 UTC, merged