fixed names
Umuzi-org/ACN-syllabus pull request #822
Opened 2022-06-21 13:25 UTC by FaithMo

Related issues: [please specify]
Issue: https://github.com/Umuzi-org/Tilde/issues/478

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-06-21 15:57 UTC, Ngoakor12 approved these changes

2022-06-22 04:43 UTC, Sbonelo01 requested changes
Hey Faith, please have a look at this PR: https://github.com/Umuzi-org/ACN-syllabus/pull/787

Please see the naming convention for JS outlined in it, do you recommend that it be changed? and snake_case used instead?

2022-06-22 05:40 UTC, FaithMo commented
> Hey Faith, please have a look at this PR: #787
> 
> Please see the naming convention for JS outlined in it, do you recommend that it be changed? and snake_case used instead?

Hey, the perfect project for simple calculator is already named like this. (snake_case)

2022-06-22 06:07 UTC, Sbonelo01 commented
> > Hey Faith, please have a look at this PR: #787
> > Please see the naming convention for JS outlined in it, do you recommend that it be changed? and snake_case used instead?
> 
> Hey, the perfect project for simple calculator is already named like this. (snake_case). Is it not that file names in the perfect project should match those in the syllabus?

Yes 💯, So do you recommend I change the content here #787 and instruct JS learners to name files and directories using snake_case because that is already the case in the automaker?

2022-06-22 19:33 UTC, Sbonelo01 approved these changes

2022-06-27 20:22 UTC, Vuyisanani approved these changes

2022-06-29 10:58 UTC, ry-oc approved these changes

2022-06-30 05:57 UTC, sheenarbw approved these changes

2022-06-30 06:01 UTC, merged