Bootcamp data eng auto boot.md
Umuzi-org/ACN-syllabus pull request #823
Opened 2022-06-21 13:56 UTC by JacobUmuzi

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-06-21 14:00 UTC, ry-oc approved these changes

2022-06-22 05:56 UTC, sheenarbw requested changes
This is good but I think maybe thee purpose of this was misunderstood.

Remember that we need something that is 100% automarked for the AWS screening. That means that if we put things on here that aren't automarked then it wont work - our staff will potentially get saddled with a code review workload for people who aren't even our learners. 

This data eng syllabus is nice for our own bootcamps BUT we need something that fits the AWS need. Can you please make another one?

2022-06-22 05:56 UTC, sheenarbw commented on content/syllabuses/bootcamp-data-eng-auto-boot.md
> +- {{% contentlink path="projects/katas/level-1" flavour="python" %}}
I'm not sure that this stuff will work for the AWS folks. We don't want any humans to have to review any of their code at all.

2022-06-24 13:24 UTC, sheenarbw approved these changes

2022-06-24 13:24 UTC, merged