fixed gramma
Umuzi-org/ACN-syllabus pull request #831
Opened 2022-07-03 21:01 UTC by rethabilethulo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-07-04 06:32 UTC, Samantha-Hampton approved these changes

2022-07-04 14:15 UTC, Andy-Nkumane approved these changes

2022-07-05 03:38 UTC, ry-oc requested changes
Sentence structure feels off

2022-07-05 03:38 UTC, ry-oc commented on content/projects/github-api-consume/_index.md
> +- Ensure that for JavaScript the function should print the output, and for python the function should return the output
would prints not work better than should print in this context, the sentence feels off.

Also, returns would probably work better than should return?

2022-07-07 06:24 UTC, ry-oc approved these changes

2022-07-08 13:13 UTC, sheenarbw approved these changes

2022-07-08 13:13 UTC, merged