#491 simple calculator part 1 project pre-requisite to validate sa id project
Umuzi-org/ACN-syllabus pull request #833
Opened 2022-07-06 04:10 UTC by Andy-Nkumane

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-07-06 19:35 UTC, Rokhuda requested changes

2022-07-06 19:35 UTC, Rokhuda commented on content/language-agnostic/validate-id-number/_index.md
> +  soft: []
Is line 14 necessary?.

2022-07-07 14:03 UTC, Rokhuda approved these changes

2022-07-07 17:17 UTC, rethabilethulo approved these changes

2022-07-08 03:22 UTC, ry-oc approved these changes

2022-07-08 03:22 UTC, merged