created new branch to avoid merge conflicts
Umuzi-org/ACN-syllabus pull request #838
Opened 2022-07-11 05:35 UTC by rethabilethulo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-07-11 09:26 UTC, Andy-Nkumane approved these changes

2022-07-18 08:44 UTC, Samantha-Hampton requested changes
Just some minor grammatical edits

2022-07-18 08:44 UTC, Samantha-Hampton commented on content/projects/data-science-specific/bootcamp-exploratory-data-analysis/_index.md
> +- Ensure that they checked if the data has any other problems and fixed the problems if they detected any problems.
"Ensure that they checked if the data has any other problems and resolved them if so."

2022-07-18 08:44 UTC, Samantha-Hampton commented on content/projects/data-science-specific/bootcamp-exploratory-data-analysis/_index.md
> +- Ensure that the notebook has an introduction at the beginning of the notebook, insights for every answered question, and a conclusion at the end of the notebook.
"Ensure that the notebook has an introduction at the beginning, insights for every answered question, and a conclusion at the end."

2022-07-18 08:44 UTC, Samantha-Hampton commented on content/projects/data-science-specific/bootcamp-exploratory-data-analysis/_index.md
> +- Ensure that all plots are labeled and the title and axis are bold.
"Ensure that all plots have their titles and axes labelled in bold."

2022-07-19 10:31 UTC, Samantha-Hampton approved these changes

2022-07-20 06:31 UTC, ry-oc approved these changes
looks good

2022-07-26 13:07 UTC, sheenarbw approved these changes

2022-07-26 13:07 UTC, merged