updated makeAllSounds method
Umuzi-org/ACN-syllabus pull request #840
Opened 2022-07-13 05:43 UTC by FaithMo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-07-13 20:30 UTC, Sbonelo01 approved these changes

2022-07-19 16:23 UTC, Vuyisanani requested changes

2022-07-19 16:23 UTC, Vuyisanani commented on content/projects/oop/animals/part1/_index.md
> +// ["Bark", "Meow", Bark]
Might have missed to add the last index in a string, you have Bark, belive should be "Bark"

2022-07-19 16:23 UTC, Vuyisanani commented on content/projects/oop/animals/part1/_index.md
> +// ["Bark", "Meow", Bark]
Might have missed to add the last index in a string, you have Bark, belive should be "Bark"

2022-07-19 16:23 UTC, Vuyisanani commented on content/projects/oop/animals/part1/_index.md
> +# ["Bark", "Meow", Bark]
Might have missed adding the last index in a string, you have Bark, believe should be "Bark"

2022-07-22 04:53 UTC, Sbonelo01 approved these changes

2022-08-10 15:02 UTC, Vuyisanani approved these changes

2022-08-16 07:02 UTC, ry-oc approved these changes

2022-08-16 14:50 UTC, sheenarbw approved these changes

2022-08-16 14:50 UTC, merged