Added instructions for the reviewer
Umuzi-org/ACN-syllabus pull request #843
Opened 2022-07-15 14:45 UTC by rethabilethulo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-07-18 05:27 UTC, Andy-Nkumane approved these changes

2022-07-18 07:31 UTC, Samantha-Hampton requested changes
Just some minor changes for consistency and correct plural version

2022-07-18 07:31 UTC, Samantha-Hampton commented on content/projects/data-science-specific/data-visualisation/linux-evolution/_index.md
> +- Ensure graphs should have titles and labelled axis.
"Ensure that all graphs have titles and labelled axes"

2022-07-18 07:31 UTC, Samantha-Hampton commented on content/projects/data-science-specific/data-visualisation/linux-evolution/_index.md
> +- Ensure that all plot titles and axis are bold.
"Ensure that all graph titles and axes labels are bold"

2022-07-19 10:37 UTC, Samantha-Hampton approved these changes

2022-07-20 06:32 UTC, ry-oc approved these changes

2022-07-26 13:09 UTC, sheenarbw approved these changes

2022-07-26 13:09 UTC, merged