Add Khan Academy statistics cards
Umuzi-org/ACN-syllabus pull request #844
Opened 2022-07-18 18:30 UTC by TheAbstract

Related issues: [Create Khan Academy statistics projects #527](https://github.com/Umuzi-org/Tilde/issues/527)

## Description:

- Added statistics topics, these will be prerequisites to the relevant basic-data-analysis assessments. 
- Removed `content/topics/khan-academy/quantitative-data-analysis/`, material referenced there is now in these specific topics, and integrated into the syllabus (no longer a stand alone topic).

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-07-19 03:32 UTC, Andy-Nkumane approved these changes

2022-07-19 11:01 UTC, Samantha-Hampton requested changes
This is awesome. Just two small things

1) The numbers for each unit come out a bit strange in the title. Not a big deal but I'm not sure why it is doing this - see screen shot
<img width="907" alt="Screenshot 2022-07-19 at 12 55 02" src="https://user-images.githubusercontent.com/50909846/179734819-61c38ea6-c065-4984-97be-b44edbce5446.png">


2) The advanced stats isn't linked anywhere as a pre-requisite (that I can see)  - just checking it's not meant to be - i.e will it just be a card on their boards?

2022-07-22 11:00 UTC, TheAbstract commented
@Samantha-Hampton yes the advanced stats isn't a prerequisite for anything right now but I've added it on the syllabus in `content/syllabuses/data-sci.md` so it will be on their boards. Still thinking about which project to link it too.

😄 I know the numbers bothered me too, but that's how they are on all the titles 🤷🏾 
![Screenshot 2022-07-22 at 12 56 09](https://user-images.githubusercontent.com/56311555/180425675-c86aefb3-36dc-4ffd-abb0-45732b2aa70f.png)

2022-07-22 11:12 UTC, Samantha-Hampton approved these changes

2022-07-27 08:04 UTC, JacobUmuzi approved these changes

2022-07-29 10:13 UTC, sheenarbw approved these changes

2022-07-29 10:14 UTC, merged