update read me for level 1 coding challenge
Umuzi-org/ACN-syllabus pull request #846
Opened 2022-07-22 14:36 UTC by ruddy-m

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-07-27 08:09 UTC, TheAbstract requested changes
@ruddy-m I think it might be better to either have consistent task function names (`task1`, `task2`, ..., `task7`) or have specific names for each task like (`combine`, `square`, etc.). 
So for example either one of these  would be fine but not a mixture of the two 
```
task1    multiples
task2    three
task3    sixtyfive
task4    square
task5    triangle
task6    longest
task7    combine
```

2022-07-27 11:21 UTC, sheenarbw requested changes
There's a little polish needed here and there. And it would be good to add something to tell the learner about the expected directory structure and file names

2022-07-27 11:21 UTC, sheenarbw commented on content/projects/katas/level-1/_index.md
>  For example, `square(2)` should print:
Write a function `task4`, name it `square`. I'm not sure if the function is meant to be named task4 or square

2022-07-27 11:21 UTC, sheenarbw commented on content/projects/katas/level-1/_index.md
>  For example, `triangle(2)` should print:
should this say `task5`? or `triangle`? I see in the automaker config you named it `triangle`, I'm just concerned that it's not consistent with all the tasks before.

2022-08-12 09:13 UTC, sheenarbw approved these changes

2022-08-12 10:13 UTC, merged