Guard against wildcard Imports
Umuzi-org/ACN-syllabus pull request #849
Opened 2022-07-27 16:42 UTC by MondeAnna

Advise against the use of wildcard imports by providing an example thereof

Related issues: clean code for Python

## Description:

We, recruits, consistently make wildcard imports when wishing to avoid having to specify exact imports. It may be wise to advise against such an act at a level higher than individual reviews.

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-08-02 10:28 UTC, ry-oc approved these changes

2022-08-04 08:49 UTC, Rokhuda requested changes

2022-08-04 08:49 UTC, Rokhuda commented on content/topics/clean-code/python/_index.md
> +
Perhaps add a little context as to why wildcard imports should be avoided.

2022-08-15 02:08 UTC, MondeAnna commented
### Morning

Context added ^_^

2022-08-16 06:15 UTC, Rokhuda requested changes
May I suggest you just add a link that provides details about wildcards?

2022-08-18 06:19 UTC, Rokhuda requested changes

2022-08-18 06:19 UTC, Rokhuda commented on content/topics/clean-code/python/_index.md
> +- Imports are sequential, thus the final wildcard's classes and functions will override whateter came before. Should this be the incorrect class or function, you will struggle to figure out why the c
Please use grammarly, there is a few grammar issues.

2022-09-07 23:24 UTC, Rokhuda requested changes

2022-09-07 23:24 UTC, Rokhuda commented on content/topics/clean-code/python/_index.md
> +In summary, wildcard imports should be avoided, as they make it unclear which names are present in the namespace, confusing both readers and many automated tools. There is one defensible use case for
It is very hard to visualize what you referring to in these examples. The Links do give better insight.

2022-09-07 23:24 UTC, Rokhuda commented on content/topics/clean-code/python/_index.md
> +Should there still be a need to import multiple aspects of a module or a module in its entirety, attempt to import submodules, ensuring unique names and dot call whatever classes or functions you des
This info is extrapolated in the links provided. Should we just point them to the links for the rest of the info?

2022-09-07 23:24 UTC, Rokhuda commented on content/topics/clean-code/python/_index.md
> +```
This can be kept

2022-11-09 07:35 UTC, TheAbstract approved these changes
Looks good 👍🏾.

2022-12-15 12:33 UTC, merged