Add information on directory structure for python version of Shopping Cart Calculations project #561
Umuzi-org/ACN-syllabus pull request #851
Opened 2022-07-28 09:54 UTC by Andy-Nkumane

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changes in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-07-28 12:34 UTC, Samantha-Hampton approved these changes

2022-07-28 16:28 UTC, rethabilethulo approved these changes

2022-08-02 06:39 UTC, ry-oc approved these changes

2022-08-02 06:48 UTC, ry-oc requested changes
Please can there be consistency between how we indent and represent folders, update the javascript to match the python.

2022-08-03 06:22 UTC, ry-oc approved these changes

2022-08-03 06:28 UTC, sheenarbw approved these changes

2022-08-03 06:28 UTC, merged