Javascript error handling best practices
Umuzi-org/ACN-syllabus pull request #858
Opened 2022-08-11 18:10 UTC by Ngoakor12

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-08-12 12:02 UTC, TheMaja requested changes

2022-08-12 12:02 UTC, TheMaja commented on content/topics/error-handling/_index.md
> +## Common bad ways people/tutorials handle errors
i will suggest this heading be more concise like the others, **bad error handling practices** or **Bad error handling** these are  brief and comprehensive.

2022-08-15 18:24 UTC, TheMaja requested changes
_well done ngoako._
- suggest you install spell checker extension.
- for words like  **_occured ,  rethrowing_** are faulty unknown words.

2022-08-18 09:27 UTC, TheMaja approved these changes

2022-10-28 02:44 UTC, KhalidUmuzi approved these changes

2022-11-09 08:05 UTC, sheenarbw approved these changes

2022-11-09 08:05 UTC, merged