Update project instructions and submission instructions
Umuzi-org/ACN-syllabus pull request #880
Opened 2022-10-25 02:51 UTC by ry-oc

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-10-25 06:18 UTC, Andy-Nkumane requested changes
getting there:
* there is some inconsistency in the table id's

2022-10-25 06:18 UTC, Andy-Nkumane commented on content/sql/shop-project/_index.md
> +Note: When creating tables you will note that each table has an ID column, when joining data between tables the foreign key must include the name of the table the data came from, i.e. `CustomerID` in
```suggestion
Note: When creating tables you will note that each table has an ID column, when joining data between tables the foreign key must include the name of the table the data came from, i.e. `ProductID` in the above table.
```

2022-10-25 06:18 UTC, Andy-Nkumane commented on content/sql/shop-project/_index.md
> +| Id (int) | ProductID (int) | PaymentID (int) | FulfilledByEmployeeID (int) | DateRequired (datetime) | DateShipped (datetime) | Status (varchar20) |
```suggestion
| ID (int) | ProductID (int) | PaymentID (int) | FulfilledByEmployeeID (int) | DateRequired (datetime) | DateShipped (datetime) | Status (varchar20) |
```

2022-10-25 06:18 UTC, Andy-Nkumane commented on content/sql/shop-project/_index.md
> +| CustomerId (int) | ID (int) | PaymentDate (datetime) | Amount (decimal) |
```suggestion
| CustomerID (int) | ID (int) | PaymentDate (datetime) | Amount (decimal) |
```

2022-10-25 06:18 UTC, Andy-Nkumane commented on content/sql/shop-project/_index.md
> +| Id (int) | ProductName (varchar100) | Description (varchar300)                                                    | BuyPrice (decimal) |
```suggestion
| ID (int) | ProductName (varchar100) | Description (varchar300)                                                    | BuyPrice (decimal) |
```

2022-10-25 06:18 UTC, Andy-Nkumane commented on content/sql/shop-project/_index.md
> +Note: When creating tables you will note that each table has an ID column, when joining data between tables the foreign key must include the name of the table the data came from, i.e. `CustomerID` in
to avoid possible confusion, it is best to be accurate as possible

2022-10-26 11:44 UTC, Samantha-Hampton requested changes

2022-10-26 11:44 UTC, Samantha-Hampton commented on content/sql/shop-project/_index.md
> +| CustomerID (int) | ID (int) | PaymentDate (datetime) | Amount (decimal) |
tiny thing but just for consistency across the tables should `ID (int)` not be the first column of the payments table?

2022-10-27 03:52 UTC, ry-oc commented on content/sql/shop-project/_index.md
> +| CustomerID (int) | ID (int) | PaymentDate (datetime) | Amount (decimal) |
good point, will change it now

2022-10-27 07:39 UTC, Samantha-Hampton approved these changes

2022-10-27 11:26 UTC, Andy-Nkumane approved these changes

2022-11-02 11:11 UTC, merged