Responsive Web Design Instruction update
Umuzi-org/ACN-syllabus pull request #881
Opened 2022-11-09 14:14 UTC by Ngoakor12

Related issues: [[FreeCodeCamp Responsive Web Design Curriculum Update: Point to specific part of the legacy course.](https://www.notion.so/FreeCodeCamp-Responsive-Web-Design-Curriculum-Update-Point-to-specific-part-of-the-legacy-course-dae7a1b395e54fa58fae8ccce6baefdf)]

## Description:
Instructions updated to be more specific with the addition of a new freecodecamp responsive web design curriculum

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-11-10 09:44 UTC, Sbonelo01 approved these changes

2022-11-10 16:20 UTC, Vuyisanani requested changes
Looking good, just one small typo, where you have 2 and in one sentence next to eat other

2022-11-10 16:20 UTC, Vuyisanani commented on content/topics/free-code-camp/responsive-web-design/4-applied-accessibility/_index.md
> +To make your profile useful, you need to go into your FreeCodeCamp settings and and set all your privacy settings to "Public".
typo double  `and`

2022-11-15 09:58 UTC, Sbonelo01 approved these changes
Requested changes have been addressed

2022-11-16 09:18 UTC, KhalidUmuzi approved these changes

2022-11-17 07:00 UTC, sheenarbw approved these changes
This is a quick fix, when in doubt, try to stay away from legacy things

2022-11-17 07:00 UTC, merged