Consume Github api instruction update
Umuzi-org/ACN-syllabus pull request #882
Opened 2022-11-09 14:58 UTC by Ngoakor12

Related issues: [[Consume Github api instruction update](https://www.notion.so/Consume-Github-api-instruction-update-837555eb075d4b85b9158826ea1aeac6)]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-11-10 08:41 UTC, Sbonelo01 approved these changes

2022-11-10 16:23 UTC, Vuyisanani approved these changes

2022-11-15 07:17 UTC, sheenarbw requested changes

2022-11-15 07:17 UTC, sheenarbw commented on content/projects/github-api-consume/_index.md
> +**Note:** Some github APIs have a limit of the number of resources they return at a time. You might be expected to implement pagination to get all resources from the APIs before filtering.
If there is a 10% chance that the learner will misinterpret the sentence, then 10% of learners will misinterpret the sentence...

Maybe be more explicit.  Eg:

```
Pagination is ... (say something about why it is a useful thing to know about). 

Please implement pagination.  Your get_pull_requests function should return a list/array of ALL the matching pull requests, not just the first page.
```

2022-11-17 02:24 UTC, Sbonelo01 requested changes
This looks good, just a few minor things around sentence structuring

2022-11-17 02:24 UTC, Sbonelo01 commented on content/projects/github-api-consume/_index.md
> +It is there to allow us to efficiently query through large data a chunk (page) at a time.
"It is there to allow us to efficiently query through large data 1 page at a time." sounds DRYer

2022-11-17 02:24 UTC, Sbonelo01 commented on content/projects/github-api-consume/_index.md
> +For example, without pagination you would have to load an entire chat history just to see the latest message sent to you (imagine you were in a group with thousands of active people, it would take a
"(imagine you were in a group with thousands of active people, it would take a while, no matter how fast your internet is)"

If there is a simpler way to say the above, please do so. Please also add a full stop to the sentence

2022-11-17 07:32 UTC, Sbonelo01 approved these changes

2022-11-18 00:21 UTC, KhalidUmuzi approved these changes

2022-11-23 12:13 UTC, sheenarbw approved these changes

2022-11-23 12:13 UTC, merged