added link
Umuzi-org/ACN-syllabus pull request #887
Opened 2022-11-29 14:52 UTC by FaithMo

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-11-30 04:55 UTC, Ngoakor12 requested changes
- Can you also update the part 1 project link aswell?
- I also had a quick look at the api and I'm not sure it makes it easy to search recipes using ingredients? It says something about csv files. Are you confident that it will work?
- The are some spelling errors with this part of the project (`labelled` should be `labeled`) and the part 1(`managment`,`applictions`,`excercise`)

2022-12-08 04:55 UTC, Ngoakor12 requested changes
almost there

2022-12-08 04:55 UTC, Ngoakor12 commented on content/projects/recipe-search/part-1/_index.md
> +This is part 1 of a project where we will be using Redux in order to build a recipe search user interface based on the [RecipePuppy API](https://api.edamam.com/api/recipes).
link text still refers to recipe puppy api

2022-12-08 14:38 UTC, Ngoakor12 approved these changes

2022-12-09 12:04 UTC, KhalidUmuzi approved these changes

2022-12-13 07:42 UTC, sheenarbw approved these changes

2022-12-13 07:42 UTC, merged