Added links to get to error handling best practices to all JS project…
Umuzi-org/ACN-syllabus pull request #889
Opened 2022-12-02 00:54 UTC by KhalidUmuzi

## Description:

Currently the best practices for error handling are not known to students and the automarker marks them as incorrect because they omit the "new" keyword when handling errors. This change makes the best practices easier to get to where it is needed.

## I solemnly swear that:

- [x] I ran the hugo server and looked at my changed in the browser with my own eyes
- [x] I ran the linter and there were no errors
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-12-02 09:49 UTC, Sbonelo01 requested changes
Hi Khalid, is there a reason why you only included the error handling links for just these two projects?

I am not 100% sure that just the links are enough for the task at hand. But if you're certain it solves the problem, please just fix the grammatical mistakes.

2022-12-02 09:49 UTC, Sbonelo01 commented on content/projects/oop/animals/part1/_index.md
> +Remember that writing code that doesnt do anything useful or doesn't serve a purpose is bad. even when handling errors, it is important to handle them correctly.
Please fix doesnt to doesn't .
Start "even" with a capital letter.

2022-12-09 05:21 UTC, KhalidUmuzi commented on content/projects/oop/animals/part1/_index.md
> +Remember that writing code that doesnt do anything useful or doesn't serve a purpose is bad. even when handling errors, it is important to handle them correctly.
> 

The Animals Project is the first project on the syllabus where error handling becomes a requirement for the automarker. However the best practices are not always being followed and the automarker is marking them wrong as a result. Password checker is also a project which the automarker needs these best practices in place.

We thought it would be best if the error handling topic was linked at the earliest possible place where it needs to be, and that is here

2022-12-09 08:35 UTC, Sbonelo01 commented on content/projects/oop/animals/part1/_index.md
> +Remember that writing code that doesnt do anything useful or doesn't serve a purpose is bad. even when handling errors, it is important to handle them correctly.
Cool cool

2022-12-09 08:36 UTC, Sbonelo01 approved these changes

2022-12-13 07:34 UTC, sheenarbw requested changes

2022-12-13 07:34 UTC, sheenarbw commented on content/projects/tdd/password-checker/part1/_index.md
> +- {{% contentlink path="topics/error-handling" %}}
Should this not be listed as a pre-requisite?

2023-01-18 09:52 UTC, closed without merging