Update _index.md
Umuzi-org/ACN-syllabus pull request #899
Opened 2022-12-13 15:59 UTC by minat-hub

Related issues: Person project python broken[https://www.notion.so/Person-project-python-broken-c6c36cad573f4bbf8be57874ed761e87]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2022-12-15 05:23 UTC, Rokhuda approved these changes

2022-12-15 12:05 UTC, sheenarbw requested changes
A small change

2022-12-15 12:05 UTC, sheenarbw commented on content/projects/oop/person/_index.md
> +    >spec
Can you please use a  consistent style for showing file hierarchies? 

I know things aren't always consistent in other places in the syllabus, but we should always try to improve things as we go.

The way you showed the Python and Java stuff is nicest

2023-01-04 11:09 UTC, sheenarbw approved these changes

2023-01-04 11:09 UTC, merged