change a few configuration to get this to work in hugo latest version
Umuzi-org/ACN-syllabus pull request #936
Opened 2023-03-12 07:30 UTC by ruddy-m

Related issues: [please specify]

## Description:

What are you up to? Fill us in :)

## I solemnly swear that:

- [ ] I ran the hugo server and looked at my changed in the browser with my own eyes
- [ ] I ran the linter and there were no errors
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code

2023-03-14 08:25 UTC, sheenarbw requested changes
I worry that if people follow the readme to install hugo then things wont work.

Can you update the docs and the installation script as well?

2023-03-17 05:35 UTC, ruddy-m commented
> I worry that if people follow the readme to install hugo then things wont work.
> 
> Can you update the docs and the installation script as well?

yeah i did want to invest the time on docs if this actually did not work on your machine or in the pipeline for some reason, so if its okay I can update the docs and the script

2023-03-17 06:41 UTC, ruddy-m commented on install_hugo.sh
> +VERSION_HUGO="0.111.3"  # this version matches the one on AWS amplify
not sure if this does match the version in AWS amplify how can I confirm that

2023-03-17 07:09 UTC, ruddy-m commented on install_hugo.sh
> +VERSION_HUGO="0.111.3"  # this version matches the one on AWS amplify
@sheenarbw

2023-03-17 11:12 UTC, merged